<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.3.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Dr. Craig P. Hutton">

  
  
  
    
  
  <meta name="description" content="1 TL;DR2 Introduction2.1 load packages3 date/time basics4 which day is it?5 reading dates6 time zones7 month names8 extracting datetime components9 days in a month10 custom date formats11 date calculations11.1 correcting excel date-to-numeric conversions12 planning a behavioural neuroscience experiment12.1 turning the planning script into a function13 Navigation14 Notes1 TL;DRDates/times are the last type of data you’ll probably work with on a fairly regular basis.">

  
  <link rel="alternate" hreflang="en-us" href="/post/2020-10-10-asgr-2-5-dates/">

  


  

  

  

  

  

  

  
  
  
  <meta name="theme-color" content="#2962ff">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

  

  
  
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700|Roboto:400,400italic,700|Roboto+Mono">
  

  
  
  
  <link rel="stylesheet" href="/css/academic.min.dd3b7994ab53a1ddaf2421ab58c1587f.css">

  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-140167948-1', 'auto');
      ga('set', 'anonymizeIp', true);
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="//www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/2020-10-10-asgr-2-5-dates/">

  
  
  
  
    
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@huttoncp">
  <meta property="twitter:creator" content="@huttoncp">
  
  <meta property="og:site_name" content="Craig Hutton, PhD">
  <meta property="og:url" content="/post/2020-10-10-asgr-2-5-dates/">
  <meta property="og:title" content="A Scientist&#39;s Guide to R: Step 2.5 - dates &amp; times | Craig Hutton, PhD">
  <meta property="og:description" content="1 TL;DR2 Introduction2.1 load packages3 date/time basics4 which day is it?5 reading dates6 time zones7 month names8 extracting datetime components9 days in a month10 custom date formats11 date calculations11.1 correcting excel date-to-numeric conversions12 planning a behavioural neuroscience experiment12.1 turning the planning script into a function13 Navigation14 Notes1 TL;DRDates/times are the last type of data you’ll probably work with on a fairly regular basis."><meta property="og:image" content="/post/2020-10-10-asgr-2-5-dates/featured.png">
  <meta property="og:locale" content="en-us">
  
  <meta property="article:published_time" content="2020-10-10T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2020-10-10T00:00:00&#43;00:00">
  

  

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
  window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#2962ff",
          "text": "#fff"
        },
        "button": {
          "background": "#fff",
          "text": "#2962ff"
        }
      },
      "theme": "classic",
      "content": {
        "message": "This website uses cookies to ensure you get the best experience on our website.",
        "dismiss": "Got it!",
        "link": "Learn more",
        "href": "/privacy/"
      }
    })});
</script>


  

  <title>A Scientist&#39;s Guide to R: Step 2.5 - dates &amp; times | Craig Hutton, PhD</title>

</head>
<body id="top" data-spy="scroll" data-target="#TableOfContents" data-offset="71" >
  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" role="textbox" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>



<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/"><img src="/img/Picture1.png" alt="Craig Hutton, PhD"></a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav mr-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#about">
            
            <span>Home</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#skills">
            
            <span>Skills</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#experience">
            
            <span>Experience</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts">
            
            <span>Posts</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#publications">
            
            <span>Publications</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#accomplishments">
            
            <span>Awards</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact">
            
            <span>Contact</span>
            
          </a>
        </li>

        
        

      
      </ul>
      <ul class="navbar-nav ml-auto">
      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  













<div class="article-header d-xl-none">
  <div class="featured-image" style="background-image: url('/post/2020-10-10-asgr-2-5-dates/featured_hu3922ef13c9d2627cf512baf19fc48074_35544_800x0_resize_lanczos_2.png');"></div>
  
</div>


<div class="container-fluid split-header d-none d-xl-block">
  <div class="row">
    <div class="col-6">
      <div class="split-header-content">
        <h1 itemprop="name">A Scientist&#39;s Guide to R: Step 2.5 - dates &amp; times</h1>

        

        



<meta content="2020-10-10 00:00:00 &#43;0000 UTC" itemprop="datePublished">
<meta content="2020-10-10 00:00:00 &#43;0000 UTC" itemprop="dateModified">

<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    <time>Oct 10, 2020</time>
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    25 min read
  </span>
  

  
  
  <span class="middot-divider"></span>
  <a href="/post/2020-10-10-asgr-2-5-dates/#disqus_thread"></a>
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder"></i>
    <a href="/categories/r/">R</a>, <a href="/categories/reproducible-research/">Reproducible Research</a>, <a href="/categories/data-cleaning-and-transformation/">Data Cleaning and Transformation</a></span>
  

  

</div>


        















        
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=A%20Scientist%27s%20Guide%20to%20R%3a%20Step%202.5%20-%20dates%20%26%20times&amp;url=%2fpost%2f2020-10-10-asgr-2-5-dates%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fpost%2f2020-10-10-asgr-2-5-dates%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-facebook-f"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fpost%2f2020-10-10-asgr-2-5-dates%2f&amp;title=A%20Scientist%27s%20Guide%20to%20R%3a%20Step%202.5%20-%20dates%20%26%20times"
         target="_blank" rel="noopener">
        <i class="fab fa-linkedin-in"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fpost%2f2020-10-10-asgr-2-5-dates%2f&amp;title=A%20Scientist%27s%20Guide%20to%20R%3a%20Step%202.5%20-%20dates%20%26%20times"
         target="_blank" rel="noopener">
        <i class="fab fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=A%20Scientist%27s%20Guide%20to%20R%3a%20Step%202.5%20-%20dates%20%26%20times&amp;body=%2fpost%2f2020-10-10-asgr-2-5-dates%2f">
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


      </div>
    </div>
    <div class="col-6">
      <div class="split-header-image">
        <img src="/post/2020-10-10-asgr-2-5-dates/featured_hu3922ef13c9d2627cf512baf19fc48074_35544_680x500_fill_q90_lanczos_smart1_2.png" itemprop="image" alt="">
        
      </div>
    </div>
  </div>
</div>

<div class="article-container d-xl-none">
  <h1 itemprop="name">A Scientist&#39;s Guide to R: Step 2.5 - dates &amp; times</h1>

  

  



<meta content="2020-10-10 00:00:00 &#43;0000 UTC" itemprop="datePublished">
<meta content="2020-10-10 00:00:00 &#43;0000 UTC" itemprop="dateModified">

<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    <time>Oct 10, 2020</time>
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    25 min read
  </span>
  

  
  
  <span class="middot-divider"></span>
  <a href="/post/2020-10-10-asgr-2-5-dates/#disqus_thread"></a>
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder"></i>
    <a href="/categories/r/">R</a>, <a href="/categories/reproducible-research/">Reproducible Research</a>, <a href="/categories/data-cleaning-and-transformation/">Data Cleaning and Transformation</a></span>
  

  
    
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=&amp;url="
         target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u="
         target="_blank" rel="noopener">
        <i class="fab fa-facebook-f"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=&amp;title="
         target="_blank" rel="noopener">
        <i class="fab fa-linkedin-in"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=&amp;title="
         target="_blank" rel="noopener">
        <i class="fab fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=&amp;body=">
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>

  














</div>



  <div class="article-container">

    <div class="article-style" itemprop="articleBody">
      

<div id="TOC">
<ul>
<li><a href="#tldr"><span class="toc-section-number">1</span> <strong>TL;DR</strong></a></li>
<li><a href="#introduction"><span class="toc-section-number">2</span> <strong>Introduction</strong></a><ul>
<li><a href="#load-packages"><span class="toc-section-number">2.1</span> load packages</a></li>
</ul></li>
<li><a href="#datetime-basics"><span class="toc-section-number">3</span> <strong>date/time basics</strong></a></li>
<li><a href="#which-day-is-it"><span class="toc-section-number">4</span> <strong>which day is it?</strong></a></li>
<li><a href="#reading-dates"><span class="toc-section-number">5</span> <strong>reading dates</strong></a></li>
<li><a href="#time-zones"><span class="toc-section-number">6</span> <strong>time zones</strong></a></li>
<li><a href="#month-names"><span class="toc-section-number">7</span> <strong>month names</strong></a></li>
<li><a href="#extracting-datetime-components"><span class="toc-section-number">8</span> <strong>extracting datetime components</strong></a></li>
<li><a href="#days-in-a-month"><span class="toc-section-number">9</span> <strong>days in a month</strong></a></li>
<li><a href="#custom-date-formats"><span class="toc-section-number">10</span> <strong>custom date formats</strong></a></li>
<li><a href="#date-calculations"><span class="toc-section-number">11</span> <strong>date calculations</strong></a><ul>
<li><a href="#correcting-excel-date-to-numeric-conversions"><span class="toc-section-number">11.1</span> correcting excel date-to-numeric conversions</a></li>
</ul></li>
<li><a href="#planning-a-behavioural-neuroscience-experiment"><span class="toc-section-number">12</span> <strong>planning a behavioural neuroscience experiment</strong></a><ul>
<li><a href="#turning-the-planning-script-into-a-function"><span class="toc-section-number">12.1</span> turning the planning script into a function</a></li>
</ul></li>
<li><a href="#navigation"><span class="toc-section-number">13</span> Navigation</a></li>
<li><a href="#notes"><span class="toc-section-number">14</span> Notes</a></li>
</ul>
</div>

<div id="tldr" class="section level1">
<h1><span class="header-section-number">1</span> <strong>TL;DR</strong></h1>
<p>Dates/times are the last type of data you’ll probably work with on a fairly regular basis. This post will show you how to use the <a href="https://lubridate.tidyverse.org/">lubridate</a> tidyverse package in R so you’ll know how to handle dates &amp; times when you encounter them.</p>
<div class="figure">
<img src="https://p1.pxfuel.com/preview/920/596/59/time-clock-alarm-clock-time-of.jpg" alt="" />
<p class="caption">image source: <a href="https://www.pxfuel.com/" class="uri">https://www.pxfuel.com/</a></p>
</div>
</div>
<div id="introduction" class="section level1">
<h1><span class="header-section-number">2</span> <strong>Introduction</strong></h1>
<p>The 9th post of the <a href="https://craig.rbind.io/post/2019-05-17-asgr-basic-workflow/">Scientist’s Guide to R series</a> covers how to work with dates and times in R. This will be the last post on data structures in R that we need to cover before we can confidently move on to more exciting things.</p>
<p>Until I learned about the <code>lubridate</code> package, dates were one of the most frustrating data structures to work. This is partly because there are many different formats that can be used to specify them and it’s not uncommon for multiple formats to be used within the same dataset if more than one person entered the data. To make things worse, when you import data from Excel dates will often be read as 5-digit numbers that can leave you wondering if the data somehow became corrupted. Part of the reason for this strangeness is that different programs use different date origins (thanks to my fellow DSS blogger <a href="https://andriy.rbind.io/">Andriy Koval</a> for pointing that out). For example, as you’ll see below, R uses January 1st of 1970 as an origin whereas Excel uses January 1st of 1900.</p>
<p>This post will show you how <code>lubridate</code> can help you overcome these sorts of problems. I’ll also demonstrate how <code>lubridate</code> can help you plan experiments.</p>
<div id="load-packages" class="section level2">
<h2><span class="header-section-number">2.1</span> load packages</h2>
<p>As usual, we’ll start by loading the packages we’ll need.</p>
<pre class="r"><code>library(tidyverse) #as usual, we&#39;ll need to use some tidyverse packages 

#while it is part of the &quot;tidyverse&quot;, `lubridate`is installed and loaded
#separately from the tidyverse meta-package

#install.packages(&quot;lubridate&quot;) #uncomment and run if you haven&#39;t installed it before
library(lubridate) </code></pre>
</div>
</div>
<div id="datetime-basics" class="section level1">
<h1><span class="header-section-number">3</span> <strong>date/time basics</strong></h1>
<p>In R, temporal data can be represented as dates, times (within a day), or a combination of a date and a time (date-time)<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>. If your data are stored as a tibble, these types will have different class labels: “date”, “time” and “dttm” respectively. Otherwise, they’ll be classified using a date/time format called <a href="https://www.stat.berkeley.edu/~s133/dates.html">“POSIXct”</a> (stands for <strong>p</strong>ortable <strong>o</strong>perating <strong>s</strong>ystem <strong>i</strong>nterface [originally designed for UNI<strong>X</strong>], <strong>c</strong>hronological <strong>t</strong>ime). There is also a “local time” version which has to do with time zones, but we won’t worry about it for now. Each of these date/time object types has a slightly different default display format (“default” because <code>lubridate</code> allows you to modify it) that determines how the values are displayed:</p>
<ul>
<li><p><strong>dates:</strong> yyyy-mm-dd (year-month-day)</p></li>
<li><p><strong>times:</strong> hh:mm:ss (hours:minutes:seconds)</p></li>
<li><p><strong>datetimes:</strong> yyyy-mm-dd hh:mm:ss</p></li>
<li><p>at the right end of times/datetimes you’ll also see an abbreviation for the time zone, which will be “UTC” by default. I’ll cover time zone details later in this post.</p></li>
</ul>
<p>Under the hood, a date object in R is stored as the number of days from January 1st of 1970, which is revealed if you convert a date to a numeric vector.</p>
<pre class="r"><code>as.Date(&quot;1970-01-01&quot;) %&gt;% 
  as.numeric()</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>as.Date(&quot;1970-01-02&quot;) %&gt;% 
  as.numeric()</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>as.Date(&quot;2020-08-29&quot;) %&gt;% 
  as.numeric()</code></pre>
<pre><code>## [1] 18503</code></pre>
<p>Wow, it’s been a lot of days since January 1st of 1970.</p>
<p>Why does R represent dates internally as integers? So you can do quick calculations with them, e.g. to get the date 100 days from August 29th, 2020:</p>
<pre class="r"><code>as.Date(&quot;2020-08-29&quot;) + 100</code></pre>
<pre><code>## [1] &quot;2020-12-07&quot;</code></pre>
<p>Calculating the number of days between 2 dates is also pretty straightforward, just subtract the earlier one from the later one:</p>
<pre class="r"><code>as.Date(&quot;2020-08-29&quot;) - as.Date(&quot;2020-01-01&quot;)</code></pre>
<pre><code>## Time difference of 241 days</code></pre>
</div>
<div id="which-day-is-it" class="section level1">
<h1><span class="header-section-number">4</span> <strong>which day is it?</strong></h1>
<p>In base R, you can also get today’s date using <code>Sys.Date()</code></p>
<pre class="r"><code>Sys.Date()</code></pre>
<pre><code>## [1] &quot;2020-10-10&quot;</code></pre>
<p>Or using the easier-to-remember <code>lubridate</code> function <code>today()</code></p>
<pre class="r"><code>today()</code></pre>
<pre><code>## [1] &quot;2020-10-10&quot;</code></pre>
<p>You can also get the current system date &amp; time using <code>base::Sys.time()</code> or <code>lubridate::now()</code></p>
<pre class="r"><code>Sys.time()</code></pre>
<pre><code>## [1] &quot;2020-10-10 00:20:37 EDT&quot;</code></pre>
<pre class="r"><code>now()</code></pre>
<pre><code>## [1] &quot;2020-10-10 00:20:37 EDT&quot;</code></pre>
</div>
<div id="reading-dates" class="section level1">
<h1><span class="header-section-number">5</span> <strong>reading dates</strong></h1>
<p>While we didn’t have any trouble turning a string into a date when it was presented in the standard format “yyyy-mm-dd”, things go awry if we try the same thing with a non-standard format like “dd-mm-yyyy”:</p>
<pre class="r"><code>as.Date(&quot;29-08-2020&quot;) %&gt;% as.numeric()</code></pre>
<pre><code>## [1] -708704</code></pre>
<p>Well that doesn’t look right!</p>
<p>To use a non-standard format with as.Date() we’ll need to specify it with the <code>format</code> argument via a combination of case-sensitive <code>%*</code> (replace * with the appropriate letter) codes of the form <code>"%Y-%m-%d"</code>, where the most common ones you may need are:</p>
<ul>
<li><p><code>%a</code> = abbreviated weekday name</p></li>
<li><p><code>%A</code> = full weekday name</p></li>
<li><p><code>%b</code> = abbreviated month name</p></li>
<li><p><code>%B</code> = full month name</p></li>
<li><p><code>%d</code> = day of the month as a 2-digit number</p></li>
<li><p><code>%D</code> = shortcut for <code>%Y/%m/%d</code></p></li>
<li><p><code>%e</code> = day of the month as a single digit number with a leading space</p></li>
<li><p><code>%H</code> or <code>%I</code> = hours as a 2-digit number</p></li>
<li><p><code>%j</code> = day of the year as a 3-digit number</p></li>
<li><p><code>%m</code> = month as a 2-digit number</p></li>
<li><p><code>%M</code> = Minute as a 2-digit number</p></li>
<li><p><code>%p</code> = AM/PM indicator to use in conjuction with hours specified via <code>%I</code> but not <code>%H</code></p></li>
<li><p><code>%S</code> = seconds as a 2-digit number</p></li>
<li><p><code>%U</code> = week of the year as a 2-digit number (using Sunday as day 1 of the week)</p></li>
<li><p><code>%T</code> = shortcut for <code>%H:%M:%S</code></p></li>
<li><p><code>%y</code> = year without the century (2-digits)</p></li>
<li><p><code>%Y</code> = year with the century</p></li>
<li><p><code>%Z</code> = time zone abbreviation as a character string</p></li>
</ul>
<p>See the strptime help documentation for more information on these codes and a complete list using <code>?strptime</code></p>
<p>To correctly parse “29-08-2020” as day-month-year using <code>as.Date()</code> we would therefore need to specify the format as follows:</p>
<pre class="r"><code>dt &lt;- as.Date(&quot;29-08-2020&quot;, format = &quot;%d-%m-%Y&quot;)

dt </code></pre>
<pre><code>## [1] &quot;2020-08-29&quot;</code></pre>
<pre class="r"><code>dt %&gt;% as.numeric()</code></pre>
<pre><code>## [1] 18503</code></pre>
<p>Now it shows up the way we expected, and is correctly represented internally as 18,503 days since January 1st of 1970 (as before) rather than -708,704.</p>
<p>As you can see, this could make date processing quite tedious, especially if you don’t work with dates or times very often or if your data use multiple formats! This is an example of the kinds of hassle that <code>lubridate</code> was created to help us overcome. Instead of having to specify the format using <code>%*</code>-codes, <code>lubridate</code> has a set of functions that make it easy to read dates in various string formats that you may encounter in raw data and convert them to the standard format</p>
<ul>
<li><p><code>ymd()</code> year, month, day</p></li>
<li><p><code>dmy()</code> day, month, year</p></li>
<li><p><code>mdy()</code> month, day, year</p></li>
</ul>
<p>These parsing functions make it quite easy to read dates, e.g.</p>
<pre class="r"><code>identical(
  ymd(&quot;2020-08-29&quot;), 
  dmy(&quot;29-08-2020&quot;)
  )</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>identical(
  ymd(&quot;2020-08-29&quot;), 
  mdy(&quot;08-29-2020&quot;)
  )</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>If you also need to specify the time, there are extensions for the above convenience functions to make that easy too. Add <code>_h</code> for hours, <code>_hm</code> for hours &amp; minutes, and <code>_hms</code> for hours, minutes, and seconds, e.g.:</p>
<pre class="r"><code>ymd_h(&quot;2020-08-29 22&quot;)</code></pre>
<pre><code>## [1] &quot;2020-08-29 22:00:00 UTC&quot;</code></pre>
<pre class="r"><code>dmy_hm(&quot;29-08-2020 22:09&quot;)</code></pre>
<pre><code>## [1] &quot;2020-08-29 22:09:00 UTC&quot;</code></pre>
<pre class="r"><code>mdy_hms(&quot;08-29-2020 22:09:19&quot;)</code></pre>
<pre><code>## [1] &quot;2020-08-29 22:09:19 UTC&quot;</code></pre>
<p>Since working with datetimes is considerably easier in <code>lubridate</code> than base R, for the sake of brevity I’ll focus on the <code>lubridate</code> approach for most of the remainder of this post. If you would like to learn more about working with datetimes in base R, see <a href="https://www.stat.berkeley.edu/~s133/dates.html">this link</a>.</p>
<p>Fortunately, these <code>lubridate</code> functions can also handle a variety of non-numeric characters between the datetime values and still parse them correctly.</p>
<pre class="r"><code>ymd(&quot;2020-08-29&quot;) == ymd(&quot;2020/08/29&quot;) </code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>ymd(&quot;2020-08-29&quot;) == ymd(&quot;2020 08 29&quot;)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>ymd(&quot;2020-08-29&quot;) ==  ymd(&quot;2020:08:29&quot;)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>ymd(&quot;2020-08-29&quot;) ==  ymd(&quot;2020$08$29&quot;)</code></pre>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="time-zones" class="section level1">
<h1><span class="header-section-number">6</span> <strong>time zones</strong></h1>
<p>To specify the time zone we can use the <code>tz</code> argument:</p>
<pre class="r"><code>ymd_h(&quot;2020-08-29 9&quot;, 
      tz = &quot;America/Vancouver&quot;) # tz = Continent/City</code></pre>
<pre><code>## [1] &quot;2020-08-29 09:00:00 PDT&quot;</code></pre>
<p>For example, you could use this to figure out what the time difference is between New York and London or Vancouver and Cairo</p>
<pre class="r"><code>ymd_h(&quot;2020-08-29 9&quot;, tz = &quot;America/New_York&quot;) - ymd_h(&quot;2020-08-29 9&quot;, tz = &quot;Europe/London&quot;)  </code></pre>
<pre><code>## Time difference of 5 hours</code></pre>
<pre class="r"><code>ymd_h(&quot;2020-08-29 9&quot;, tz = &quot;America/Vancouver&quot;) - ymd_h(&quot;2020-08-29 9&quot;, tz = &quot;Africa/Cairo&quot;)  </code></pre>
<pre><code>## Time difference of 9 hours</code></pre>
<p>A list of time zone names can be found on <a href="https://en.wikipedia.org/wiki/List_of_tz_database_time_zones">this wikipedia page</a>.</p>
</div>
<div id="month-names" class="section level1">
<h1><span class="header-section-number">7</span> <strong>month names</strong></h1>
<p><code>lubridate</code> functions can even parse the month names if they’re provided instead of a fully numeric date string.</p>
<pre class="r"><code>mdy(&quot;October 31st, 2020&quot;)</code></pre>
<pre><code>## [1] &quot;2020-10-31&quot;</code></pre>
<pre class="r"><code>dmy(&quot;the 1st of December 2011&quot;)</code></pre>
<pre><code>## [1] &quot;2011-12-01&quot;</code></pre>
</div>
<div id="extracting-datetime-components" class="section level1">
<h1><span class="header-section-number">8</span> <strong>extracting datetime components</strong></h1>
<p><code>lubridate</code> also provides a number of self-explanatory functions for extracting some of the information from a date or datetime:</p>
<pre class="r"><code>dt &lt;- ymd_hms(&quot;2020-08-29 22:09:19&quot;)

year(dt)</code></pre>
<pre><code>## [1] 2020</code></pre>
<pre class="r"><code>month(dt)</code></pre>
<pre><code>## [1] 8</code></pre>
<pre class="r"><code>day(dt)</code></pre>
<pre><code>## [1] 29</code></pre>
<pre class="r"><code>hour(dt)</code></pre>
<pre><code>## [1] 22</code></pre>
<pre class="r"><code>minute(dt)</code></pre>
<pre><code>## [1] 9</code></pre>
<pre class="r"><code>second(dt)</code></pre>
<pre><code>## [1] 19</code></pre>
<pre class="r"><code>week(dt) #week of the year</code></pre>
<pre><code>## [1] 35</code></pre>
<pre class="r"><code>wday(dt) #day of the week, numeric</code></pre>
<pre><code>## [1] 7</code></pre>
<pre class="r"><code>wday(dt,#day of the week
     label = TRUE, #as a factor level
     abbr = FALSE) #not abbreviated</code></pre>
<pre><code>## [1] Saturday
## 7 Levels: Sunday &lt; Monday &lt; Tuesday &lt; Wednesday &lt; Thursday &lt; ... &lt; Saturday</code></pre>
<pre class="r"><code>#day of the month, this one isn&#39;t really useful since it gives you the same
#thing as day()
mday(dt) </code></pre>
<pre><code>## [1] 29</code></pre>
<pre class="r"><code>yday(dt) #day of the year</code></pre>
<pre><code>## [1] 242</code></pre>
</div>
<div id="days-in-a-month" class="section level1">
<h1><span class="header-section-number">9</span> <strong>days in a month</strong></h1>
<p>There is also a <code>lubridate</code> function which tells you how many days there are in a specified month if you haven’t yet memorized them all.</p>
<pre class="r"><code>days_in_month(dt) #the month specified in a datetime object</code></pre>
<pre><code>## Aug 
##  31</code></pre>
<pre class="r"><code>days_in_month(3) #or whichever month you want to specify</code></pre>
<pre><code>## Mar 
##  31</code></pre>
<pre class="r"><code>days_in_month(1:12) #or all months at once</code></pre>
<pre><code>## Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec 
##  31  28  31  30  31  30  31  31  30  31  30  31</code></pre>
</div>
<div id="custom-date-formats" class="section level1">
<h1><span class="header-section-number">10</span> <strong>custom date formats</strong></h1>
<p>If you’d prefer to have dates displayed differently from the standard/default yyyy-mm-dd format, you can specify an alternative format to use with the <code>lubridate::stamp_date()</code> function. This could be useful if you want the dates to follow a specific format that is used in your lab or workplace.</p>
<pre class="r"><code>#step 1: specify the format using an arbitrary date with stamp_date()
my_stamp &lt;- stamp_date(&quot;January 7th, 2019&quot;) 

#step 2: apply the format to a date object
my_stamp(dt)</code></pre>
<pre><code>## [1] &quot;August 29th, 2020&quot;</code></pre>
<pre class="r"><code>#if there are multiple possibilities lubridate will use the most probable/common one</code></pre>
<p>The alternative way of changing the display format is to apply the base R <code>format()</code> function to a datetime object and specify the format using the <code>%</code>-codes, e.g.</p>
<pre class="r"><code>format(dt, &quot;%B %dth, %Y&quot;)</code></pre>
<pre><code>## [1] &quot;August 29th, 2020&quot;</code></pre>
<p>Again, the <code>lubridate</code> version is a bit easier.</p>
</div>
<div id="date-calculations" class="section level1">
<h1><span class="header-section-number">11</span> <strong>date calculations</strong></h1>
<p>You can add days to a date that’s been processed using <code>lubridate</code> just as easily as we did using the base R <code>as.Date()</code> function</p>
<pre class="r"><code>dt &lt;- ymd(&quot;2020/08/30&quot;)

dt + 10</code></pre>
<pre><code>## [1] &quot;2020-09-09&quot;</code></pre>
<p>A raw number added to a date is interpreted as a request to add the smallest unit of time to the object that is already represented in it. You could instead specify the unit to add (weeks, month, years, etc) to a date with some intuitively-named <code>lubridate</code> helper functions:</p>
<pre class="r"><code>ymd(&quot;2020/08/30&quot;) + 10 #adds 10 days</code></pre>
<pre><code>## [1] &quot;2020-09-09&quot;</code></pre>
<pre class="r"><code>ymd_hms(&quot;2020/08/30 10:12:58&quot;) + 10 #adds 10 seconds</code></pre>
<pre><code>## [1] &quot;2020-08-30 10:13:08 UTC&quot;</code></pre>
<pre class="r"><code>ymd_hms(&quot;2020/08/30 10:12:58&quot;) + days(10) #adds 10 days instead of seconds</code></pre>
<pre><code>## [1] &quot;2020-09-09 10:12:58 UTC&quot;</code></pre>
<pre class="r"><code>ymd(&quot;2020/08/30&quot;) + weeks(1) #adds 1 week</code></pre>
<pre><code>## [1] &quot;2020-09-06&quot;</code></pre>
<pre class="r"><code>ymd(&quot;2020/08/30&quot;) - months(100) #subtracts 100 months</code></pre>
<pre><code>## [1] &quot;2012-04-30&quot;</code></pre>
<pre class="r"><code>ymd(&quot;2020/08/30&quot;) + years(80) #adds 80 years</code></pre>
<pre><code>## [1] &quot;2100-08-30&quot;</code></pre>
<p><strong><em>N.B.</em></strong> As was recently pointed out by one of my talented colleagues, <a href="https://samalbers.science/">Sam Albers</a>, if you’re adding <code>months()</code> to 29th or later day of the month and the new date doesn’t exist you’ll get an <code>NA</code> value, e.g.</p>
<pre class="r"><code>ymd(&quot;2020-10-31&quot;) + months(1)</code></pre>
<pre><code>## [1] NA</code></pre>
<p>There is no November 31st, so an <code>NA</code> is returned. If we were hoping to get a sensible result like the 30th of November or 1st day of December we’d be disappointed. To fix this and get the nearest day (rounded down), you should instead use the lubridate <code>%m+%</code> operator, or the <code>add_with_rollback()</code> function.</p>
<pre class="r"><code>ymd(&quot;2020-10-31&quot;) %m+% months(1)</code></pre>
<pre><code>## [1] &quot;2020-11-30&quot;</code></pre>
<pre class="r"><code>add_with_rollback(ymd(&quot;2020-10-31&quot;), months(1))</code></pre>
<pre><code>## [1] &quot;2020-11-30&quot;</code></pre>
<p>To roll forward instead of backwards, we can also use <code>add_with_rollback()</code> but this time we set the <code>roll_to_first</code> argument to <code>TRUE</code></p>
<pre class="r"><code>add_with_rollback(ymd(&quot;2020-10-31&quot;), months(1), roll_to_first = TRUE)</code></pre>
<pre><code>## [1] &quot;2020-12-01&quot;</code></pre>
<p>Alongside <code>%m+%</code> is a <code>%m-%</code> operator that subtracts months without rolling over to another month.</p>
<p>You can even add vectors of set intervals. For example, if you had a weekly meeting for the next 10 weeks and wanted to know the dates of each of them, you could use:</p>
<pre class="r"><code>ymd(&quot;2020/08/30&quot;) + 
  weeks(1)*c(1:10) #1 week unit for the interval * vector of meeting indices/values</code></pre>
<pre><code>##  [1] &quot;2020-09-06&quot; &quot;2020-09-13&quot; &quot;2020-09-20&quot; &quot;2020-09-27&quot; &quot;2020-10-04&quot;
##  [6] &quot;2020-10-11&quot; &quot;2020-10-18&quot; &quot;2020-10-25&quot; &quot;2020-11-01&quot; &quot;2020-11-08&quot;</code></pre>
<pre class="r"><code>#if you were given a vector of dates and wanted to know which days of the week
#they fell on you can easily get that too. e.g. if you had a meeting on the 15th
#of every month...
meeting_dates &lt;- ydm(
  stringr::str_c(&quot;2020-15-&quot;, 1:12)
) 

meeting_dates</code></pre>
<pre><code>##  [1] &quot;2020-01-15&quot; &quot;2020-02-15&quot; &quot;2020-03-15&quot; &quot;2020-04-15&quot; &quot;2020-05-15&quot;
##  [6] &quot;2020-06-15&quot; &quot;2020-07-15&quot; &quot;2020-08-15&quot; &quot;2020-09-15&quot; &quot;2020-10-15&quot;
## [11] &quot;2020-11-15&quot; &quot;2020-12-15&quot;</code></pre>
<pre class="r"><code>meeting_dates %&gt;% wday(label = TRUE)</code></pre>
<pre><code>##  [1] Wed Sat Sun Wed Fri Mon Wed Sat Tue Thu Sun Tue
## Levels: Sun &lt; Mon &lt; Tue &lt; Wed &lt; Thu &lt; Fri &lt; Sat</code></pre>
<pre class="r"><code>#or you could apply a date_stamp to them, which could be useful for populating
#an excel report or data collection sheet.
my_stamp &lt;- stamp_date(&quot;Monday, January 7th, 2019&quot;) 

meeting_dates %&gt;% my_stamp()</code></pre>
<pre><code>##  [1] &quot;Wednesday, January 15th, 2020&quot; &quot;Saturday, February 15th, 2020&quot;
##  [3] &quot;Sunday, March 15th, 2020&quot;      &quot;Wednesday, April 15th, 2020&quot;  
##  [5] &quot;Friday, May 15th, 2020&quot;        &quot;Monday, June 15th, 2020&quot;      
##  [7] &quot;Wednesday, July 15th, 2020&quot;    &quot;Saturday, August 15th, 2020&quot;  
##  [9] &quot;Tuesday, September 15th, 2020&quot; &quot;Thursday, October 15th, 2020&quot; 
## [11] &quot;Sunday, November 15th, 2020&quot;   &quot;Tuesday, December 15th, 2020&quot;</code></pre>
<p>You can also get the interval between two dates in the unit(s) of your choice using the <code>lubridate::interval()</code> &amp; <code>lubridate::time_length()</code> functions together.</p>
<pre class="r"><code>#step 1: define an interval using lubridate::interval()
int &lt;- interval(mdy(&quot;12-01-2005&quot;), today())

#step 2: use time_length(interval) and the &quot;unit&quot; argument
time_length(int, unit = &quot;day&quot;) #interval length in days</code></pre>
<pre><code>## [1] 5427</code></pre>
<pre class="r"><code>time_length(int, unit = &quot;month&quot;) #interval length in months</code></pre>
<pre><code>## [1] 178.2903</code></pre>
<pre class="r"><code>time_length(int, unit = &quot;year&quot;) #interval length in years</code></pre>
<pre><code>## [1] 14.85792</code></pre>
<pre class="r"><code>time_length(int, unit = c(&quot;day&quot;, &quot;week&quot;, &quot;month&quot;, &quot;year&quot;)) #you can also ask for multiple formats at once</code></pre>
<pre><code>## Warning in if (unit %in% c(&quot;year&quot;, &quot;month&quot;)) {: the condition has length &gt; 1 and
## only the first element will be used</code></pre>
<pre><code>## [1] 5427.00000  775.28571  178.29979   14.85832</code></pre>
<pre class="r"><code>interval(ymd_h(&quot;2020-08-27 10&quot;), now()) %&gt;% 
  time_length(unit = &quot;hour&quot;) #interval length in hours</code></pre>
<pre><code>## [1] 1050.344</code></pre>
<pre class="r"><code>#of course you can also get the difference in days by just subtracting one date
#from the other as we did earlier using base R functions
mdy(&quot;12-10-2005&quot;) - mdy(&quot;12-01-2005&quot;)</code></pre>
<pre><code>## Time difference of 9 days</code></pre>
<div id="correcting-excel-date-to-numeric-conversions" class="section level2">
<h2><span class="header-section-number">11.1</span> correcting excel date-to-numeric conversions</h2>
<p>Although it isn’t part of <code>lubridate</code>, there is a function from the <a href="http://sfirke.github.io/janitor/index.html">janitor</a> package called <code>excel_numeric_to_date()</code> that can help. For example, May 20th of 2016 may have looked like “2016-05-20” in the .xlsx file when you looked at it, but then when it gets imported into R, it appears as the mysterious number 42510 instead. This is an unfortunate issue that sometimes occurs when trying to read data from excel files specifically. The <code>excel_numeric_to_date()</code> simply converts these 5-digit date codes back to the string date format you were expecting.</p>
<pre class="r"><code>janitor::excel_numeric_to_date(42510)</code></pre>
<pre><code>## [1] &quot;2016-05-20&quot;</code></pre>
<pre class="r"><code>#also works with vectors
janitor::excel_numeric_to_date(
  c(42510:42520)
)</code></pre>
<pre><code>##  [1] &quot;2016-05-20&quot; &quot;2016-05-21&quot; &quot;2016-05-22&quot; &quot;2016-05-23&quot; &quot;2016-05-24&quot;
##  [6] &quot;2016-05-25&quot; &quot;2016-05-26&quot; &quot;2016-05-27&quot; &quot;2016-05-28&quot; &quot;2016-05-29&quot;
## [11] &quot;2016-05-30&quot;</code></pre>
</div>
</div>
<div id="planning-a-behavioural-neuroscience-experiment" class="section level1">
<h1><span class="header-section-number">12</span> <strong>planning a behavioural neuroscience experiment</strong></h1>
<p>Before I transitioned to working as a data scientist for the BC Government I spent some time doing behavioural neuroscience research. One of the first things I needed to do to conduct an experiment was figure out when I needed to do different things in the lab. I used R to make this process easier and help sort out which days I would need to reserve lab equipment and other resources.</p>
<p>I started by defining some key parameters such as the sample size per group and the number of treatment conditions I planned to use in my design. These parameters mattered because they would determine how many days some aspects of the experiment would take.</p>
<p>For this demo, we’ll plan an experiment with rats that uses an aerobic exercise intervention (for half of the animals, selected at random) that lasts 4 weeks, followed by 7 days of behavioural testing in the Barnes Maze (a test of spatial learning and memory for rodents), and then electrophysiological slice recordings to see if we can pickup any changes in neural signalling that might be related to the behavioural effects of the exercise intervention. <em>Feel free to copy this script and adapt it for your own purposes.</em></p>
<p>To plan out this hypothetical experiment, we’ll need to define some parameters of the study design that affect scheduling, summarized as follows:</p>
<ul>
<li><p>most obviously, which day we plan to start the experiment</p></li>
<li><p>the desired sample size and number of experimental groups, which may affect how long some parts of the experiment take based on the available lab equipment (e.g. the number of electrophysiology rigs in the lab)</p></li>
<li><p>whether or not we’ll be breeding the model species we need (rats in this case) or ordering it</p></li>
<li><p>how many days our experimental intervention or treatment will take to administer</p></li>
<li><p>how many days our Barnes maze protocol is</p></li>
<li><p>if we’re measuring neural activity in this experiment using electrophysiology, and how many rigs we plan to use at once</p></li>
</ul>
<p>Then we’ll need to perform the necessary operations on those parameters using a combination of functions from lubridate, functions from tidyverse packages we’ve seen in previous posts, and a bit of base R code.</p>
<p>To semi-automate this process, a first code block can be used to define parameters and a second one can describe the operations we need to perform on them.</p>
<pre class="r"><code>#sample parameters####

#how many total experimental groups will be included; if you&#39;re planning to use
#both sexes and consider biological sex as a factor in your analyses double it.
n.groups &lt;- 4

#desired sample size. This is something to discuss with your PI, but I usually
#tried to aim for at least 12 when examining behaviour
group.n &lt;- 12

#timing parameters####

#to generate animals, start breeding 1 month before experiment begins. replace
#with desired start day, month, and year
start.date  &lt;- dmy(&quot;07-09-2020&quot;) 

breeding &lt;- TRUE #will you be breeding the animals needed for this experiment?
#if you aren&#39;t breeding animals, I&#39;ll assume they are being ordered from a
#commercial breeder, in which case we&#39;ll use the estimated delivery date as the
#start date

intervention_days &lt;- 28  #how many days will the experimental intervention take?

b.testing_days &lt;- 7 #how many days will the behavioural testing take?

#Are you doing electophysiology? Estimate about 2 days per animal per
#available e-phys rig
ephys &lt;- TRUE
ephys.rigs &lt;- 4

#display parameter####
#provide an example of how you would like the dates displayed
my_stamp &lt;- stamp_date(&quot;Saturday, August 29th, 2020&quot;) </code></pre>
<p>From this point we can just run the script below and we’ll end up with an approximate schedule for our hypothetical behavioural neuroscience experiment. Don’t worry too much about the details of the conditional (<code>if</code>, <code>else if</code>, <code>else</code>) statements, we’ll cover that in a later post on R programming, although below we’ll take a first look at how to define a function.</p>
<pre class="r"><code>exp_timeline &lt;- list() #define a list to hold experimental protocol components

#animal breeding####

#we&#39;ll store a version with modified display formatting separately so we can
#still perform calculations on d0
exp_timeline[[&quot;start_date&quot;]] &lt;- my_stamp(start.date) 

if(breeding == TRUE) {
  dob &lt;- start.date+28 #pups born
  exp_timeline[[&quot;pups_born&quot;]] &lt;- my_stamp(dob)
  #approximate weaning date####
  wd &lt;- dob + 21
  exp_timeline[[&quot;pups_weaned&quot;]] &lt;- my_stamp(wd)
}

#acclimatization period####

#acclimatization to maternal separation (if bred in house) or arrival at the
#animal facility (if ordered) (usually 1 week). After this point your animals
#are ready to participate in a behavioural experiment
if(breeding == TRUE) {
  ready.date &lt;- wd + 7  
  exp_timeline[[&quot;ready_date&quot;]] &lt;- my_stamp(ready.date)
} else {
  ready.date &lt;- start.date + 7
  exp_timeline[[&quot;ready_date&quot;]] &lt;- my_stamp(ready.date)
}

#intervention protocol####
if (intervention_days &gt; 0) {
  i.ds &lt;- ready.date + c(1:intervention_days)
  exp_timeline[[&quot;intervention&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,  
                                                                      c(1:intervention_days)), 
                                               &quot;date&quot; = my_stamp(i.ds))
  
}

#behavioural testing days####
#starting the day after the intervention is complete. if you haven&#39;t been
#handling the animals throughout the intervention period for at least 1 week
#then add as many days as needed to ensure the animals have been handled for at
#least 1 week
if (b.testing_days &gt; 0) {
  if (intervention_days &gt; 0) {
    if (intervention_days &lt; 7) {
      handling_days &lt;- 7 - intervention_days
      h.ds &lt;- i.ds[intervention_days] + c(1:handling_days)
      b.ds &lt;- h.ds[handling_days] + c(1:b.testing_days)
    } else {
      b.ds &lt;- i.ds[intervention_days] + c(1:b.testing_days)
    }
  } else if (intervention_days == 0) { 
    #if you were just doing behavioural testing an no postnatal intervention
    #e.g. for a transgenic to wild-type model comparison
    
    #add a week for handling where they should be handled for at least 1 minute
    #each per day for at least 5 of the days in the &quot;handling&quot; week
    handling_days &lt;- 7
    h.ds &lt;- ready.date + c(1:handling_days)
    
    b.ds &lt;- h.ds[7] + c(1:b.testing_days)
  }
  if (exists(&quot;h.ds&quot;)) {
    exp_timeline[[&quot;animal_handling&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,  
                                                                           c(1:handling_days)), 
                                                    &quot;date&quot; = my_stamp(h.ds))    
  } 
  exp_timeline[[&quot;behavioural_testing&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,  
                                                                             c(1:b.testing_days)), 
                                                      &quot;date&quot; = my_stamp(b.ds))
}

#electrophysiology days###
#for an exercise intervention study we could start doing e-phys the day after behavioural testing is complete

totaln &lt;- n.groups*group.n #need to know how many total animals there are

if (ephys == T) {
  ephys.days &lt;- (totaln/2)/ephys.rigs
  
  if (b.testing_days &gt; 0) {
    e.ds &lt;- b.ds[b.testing_days] + c(1:ephys.days)
  } else if (b.testing_days == 0 &amp; intervention_days &gt; 0) { #if you only did an intervention
    e.ds &lt;- i.ds[intervention_days] + c(1:ephys.days)
  } else if (b.testing_days == 0 &amp; intervention_days == 0) { #if you&#39;re only doing e-phys
    e.ds &lt;- ready.date + c(1:ephys.days)
  }
  
  exp_timeline[[&quot;electrophysiology&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,
                                                                           c(1:ephys.days)), 
                                                    &quot;date&quot; = my_stamp(e.ds))
}

#determine how many days the experiment will take to complete up to the end of data collection####
if (exists(&quot;e.ds&quot;)) {
  exp_timeline[[&quot;total_days&quot;]] &lt;- e.ds[ephys.days] - start.date
  
} else if (exists(&quot;b.ds&quot;)) {
  exp_timeline[[&quot;total_days&quot;]] &lt;- b.ds[b.testing_days] - start.date
  
} else if (&quot;i.ds&quot;) { #if you only used an intervention and finished collecting data when it was over
  exp_timeline[[&quot;total_days&quot;]] &lt;- i.ds[intervention_days] - start.date
  
} </code></pre>
<p>After defining the parameters to use in constructing our experimental timeline and running the script, all we have to do to see it is print it to the console:</p>
<pre class="r"><code>exp_timeline</code></pre>
<pre><code>## $start_date
## [1] &quot;Monday, September 07th, 2020&quot;
## 
## $pups_born
## [1] &quot;Monday, October 05th, 2020&quot;
## 
## $pups_weaned
## [1] &quot;Monday, October 26th, 2020&quot;
## 
## $ready_date
## [1] &quot;Monday, November 02th, 2020&quot;
## 
## $intervention
##    protocol_day                           date
## 1        day #1   Tuesday, November 03th, 2020
## 2        day #2 Wednesday, November 04th, 2020
## 3        day #3  Thursday, November 05th, 2020
## 4        day #4    Friday, November 06th, 2020
## 5        day #5  Saturday, November 07th, 2020
## 6        day #6    Sunday, November 08th, 2020
## 7        day #7    Monday, November 09th, 2020
## 8        day #8   Tuesday, November 10th, 2020
## 9        day #9 Wednesday, November 11th, 2020
## 10      day #10  Thursday, November 12th, 2020
## 11      day #11    Friday, November 13th, 2020
## 12      day #12  Saturday, November 14th, 2020
## 13      day #13    Sunday, November 15th, 2020
## 14      day #14    Monday, November 16th, 2020
## 15      day #15   Tuesday, November 17th, 2020
## 16      day #16 Wednesday, November 18th, 2020
## 17      day #17  Thursday, November 19th, 2020
## 18      day #18    Friday, November 20th, 2020
## 19      day #19  Saturday, November 21th, 2020
## 20      day #20    Sunday, November 22th, 2020
## 21      day #21    Monday, November 23th, 2020
## 22      day #22   Tuesday, November 24th, 2020
## 23      day #23 Wednesday, November 25th, 2020
## 24      day #24  Thursday, November 26th, 2020
## 25      day #25    Friday, November 27th, 2020
## 26      day #26  Saturday, November 28th, 2020
## 27      day #27    Sunday, November 29th, 2020
## 28      day #28    Monday, November 30th, 2020
## 
## $behavioural_testing
##   protocol_day                           date
## 1       day #1   Tuesday, December 01th, 2020
## 2       day #2 Wednesday, December 02th, 2020
## 3       day #3  Thursday, December 03th, 2020
## 4       day #4    Friday, December 04th, 2020
## 5       day #5  Saturday, December 05th, 2020
## 6       day #6    Sunday, December 06th, 2020
## 7       day #7    Monday, December 07th, 2020
## 
## $electrophysiology
##   protocol_day                           date
## 1       day #1   Tuesday, December 08th, 2020
## 2       day #2 Wednesday, December 09th, 2020
## 3       day #3  Thursday, December 10th, 2020
## 4       day #4    Friday, December 11th, 2020
## 5       day #5  Saturday, December 12th, 2020
## 6       day #6    Sunday, December 13th, 2020
## 
## $total_days
## Time difference of 97 days</code></pre>
<p>Voila! There you have it. If you were doing this experiment, you’d know approximately which days each step of the protocol would fall on and how long it would take to get your data!</p>
<div id="turning-the-planning-script-into-a-function" class="section level2">
<h2><span class="header-section-number">12.1</span> turning the planning script into a function</h2>
<p>If we ran these sorts of experiments frequently, eventually we would probably want to combine these pieces into a custom scheduling function. While having all of the code in the script provides full transparency, it also makes the method a bit fragile (especially if you’re not using version control [you should always use some form of version control to save your work!]). Writing a function, documenting it, and putting it into a package is a much better (and more easily shared) long term option. The source code of an R function can of course still be inspected after all.</p>
<p>Functionalizing our experiment planning script actually isn’t too much extra work once we’ve gotten this far. We basically just need to convert the “parameter definitions” code block into a set of arguments to the special base R function, <code>"function()"</code>, copy and paste the “operations” code block into the function body, and assign a name to the result. For this example, I’ll use the name “plan_bn_exp” (for “<strong>plan</strong> a <strong>b</strong>ehavioural <strong>n</strong>euroscience <strong>exp</strong>eriment”).</p>
<pre class="r"><code>plan_bn_exp &lt;- function(#call function() &amp; assign to desired name
  #then specify arguments the user can modify between the parentheses
  
  #note: the ones without a default value, set using`=` (as below), require the user
  #to specify a value
  start_dmy, #this name makes it clear which format to use
  intervention_days,
  behav_days,
  n_groups,
  group_n,
  #if some of these don&#39;t change very often between
  #experiments, you might want to set default values for
  #them
  date_stamp = &quot;Saturday, August 29th, 2020&quot;,
  breeding = TRUE,
  ephys = TRUE,
  ephys_rigs = 4
) {
  #then in the section between the curly braces {}, called the &quot;body&quot; of the
  #function, you define what happens to the argument inputs, which in this case
  #just means copying/pasting the relevant code block from above
  
  start.date  &lt;- dmy(start_dmy) 
  
  exp_timeline &lt;- list() 
  
  exp_timeline[[&quot;start_date&quot;]] &lt;- my_stamp(start.date) 
  
  if(breeding == TRUE) {
    dob &lt;- start.date+28
    exp_timeline[[&quot;pups_born&quot;]] &lt;- my_stamp(dob)
    wd &lt;- dob + 21
    exp_timeline[[&quot;pups_weaned&quot;]] &lt;- my_stamp(wd)
  }
  if(breeding == TRUE) {
    ready.date &lt;- wd + 7  
    exp_timeline[[&quot;ready_date&quot;]] &lt;- my_stamp(ready.date)
  } else {
    ready.date &lt;- start.date + 7
    exp_timeline[[&quot;ready_date&quot;]] &lt;- my_stamp(ready.date)
  }
  
  if (intervention_days &gt; 0) {
    i.ds &lt;- ready.date + c(1:intervention_days)
    exp_timeline[[&quot;intervention&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,  
                                                                        c(1:intervention_days)), 
                                                 &quot;date&quot; = my_stamp(i.ds))
  }
  if (b.testing_days &gt; 0) {
    if (intervention_days &gt; 0) {
      if (intervention_days &lt; 7) {
        handling_days &lt;- 7 - intervention_days
        h.ds &lt;- i.ds[intervention_days] + c(1:handling_days)
        b.ds &lt;- h.ds[handling_days] + c(1:b.testing_days)
      } else {
        b.ds &lt;- i.ds[intervention_days] + c(1:b.testing_days)
      }
    } else if (intervention_days == 0) { 
      handling_days &lt;- 7
      h.ds &lt;- ready.date + c(1:handling_days)
      
      b.ds &lt;- h.ds[7] + c(1:b.testing_days)
    }
    if (exists(&quot;h.ds&quot;)) {
      exp_timeline[[&quot;animal_handling&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,  
                                                                             c(1:handling_days)), 
                                                      &quot;date&quot; = my_stamp(h.ds))    
    } 
    exp_timeline[[&quot;behavioural_testing&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,  
                                                                               c(1:b.testing_days)), 
                                                        &quot;date&quot; = my_stamp(b.ds))
  }
  
  totaln &lt;- n.groups*group.n 
  
  if (ephys == T) {
    ephys.days &lt;- (totaln/2)/ephys.rigs
    
    if (b.testing_days &gt; 0) {
      e.ds &lt;- b.ds[b.testing_days] + c(1:ephys.days)
    } else if (b.testing_days == 0 &amp; intervention_days &gt; 0) {
      e.ds &lt;- i.ds[intervention_days] + c(1:ephys.days)
    } else if (b.testing_days == 0 &amp; intervention_days == 0) { 
      e.ds &lt;- ready.date + c(1:ephys.days)
    }
    exp_timeline[[&quot;electrophysiology&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,
                                                                             c(1:ephys.days)), 
                                                      &quot;date&quot; = my_stamp(e.ds))
  }
  if (exists(&quot;e.ds&quot;)) {
    exp_timeline[[&quot;total_days&quot;]] &lt;- e.ds[ephys.days] - start.date
    
  } else if (exists(&quot;b.ds&quot;)) {
    exp_timeline[[&quot;total_days&quot;]] &lt;- b.ds[b.testing_days] - start.date
    
  } else if (&quot;i.ds&quot;) {
    exp_timeline[[&quot;total_days&quot;]] &lt;- i.ds[intervention_days] - start.date
    
  } 
  #a final piece that is often a good idea to include (but not always strictly
  #needed) is to tell the function which object to return() as a result
  return(exp_timeline)
  
}</code></pre>
<p>Then we can use the new function by calling it like any other R function (<code>plan_bn_exp(args)</code>) and check that the output is the same. Doing things this way has the big advantage of letting us focus on the parts of the planning that we need to, i.e. the key parameters of our experimental design (assuming our experiments follow consistent protocols). It also reduces the chances that we’ll accidentally break the code when editing it to input the values (as we might via the non-functional version above) .</p>
<pre class="r"><code>fun_exp_timeline &lt;- plan_bn_exp(start_dmy = &quot;07-09-2020&quot;,
                                intervention_days = 28,
                                behav_days = 28,
                                n_groups = 4, group_n = 12)

#rather than print it all again, I&#39;ll just check to make sure the output is the
#same
all.equal(exp_timeline, fun_exp_timeline)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Now you’ve learned a bit about how R programming can help you automate the process of planning a behavioural neuroscience experiment. If you were going to build a package around a function like this you’d want to do things a bit differently, but that’s a story for another post. If any grad students in psychology or neuroscience labs are reading this, some of you may even be looking forward to how much time you’ll save with these new time-processing skills under your belt. Student or not, after reading this I hope you can see that working with dates in R can be pretty easy when you leverage the <code>lubridate</code> package and you’ve even learned a few ways that they may benefit your research.</p>
</div>
</div>
<div id="navigation" class="section level1">
<h1><span class="header-section-number">13</span> Navigation</h1>
<p>Click <a href="https://craig.rbind.io/post/2020-08-29-asgr-2-4-factors/">here</a> to go back to the previous post on factors. A link to the next one will be added as soon as I have time to write it.</p>
</div>
<div id="notes" class="section level1">
<h1><span class="header-section-number">14</span> Notes</h1>
<ul>
<li><p>If you want to go beyond basic date-based operations and calculations and can’t wait to learn about related analytical techniques like time-series analysis &amp; forecasting, I highly recommended checking out <a href="https://otexts.com/fpp3/">Forecasting: Principles and Practice</a> by Rob J. Hyndman and George Athanasopoulos at Monash University.</p></li>
<li><p>If you can’t wait to learn more about how to write your own R functions, you may be interested in this chapter of <a href="https://r4ds.had.co.nz/functions.html">R4DS</a></p></li>
</ul>
<p>Thank you for visiting my blog. I welcome any suggestions for future posts, comments or other feedback you might have. Feedback from beginners and science students/trainees (or with them in mind) is especially helpful in the interest of making this guide even better for them.</p>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p><a href="https://r4ds.had.co.nz/dates-and-times.html#creating-datetimes" class="uri">https://r4ds.had.co.nz/dates-and-times.html#creating-datetimes</a><a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

    </div>

    

<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/r/">R</a>
  
  <a class="badge badge-light" href="/tags/r-basics/">R basics</a>
  
</div>



    
      








  





  
  <div class="media author-card" itemscope itemtype="http://schema.org/Person">
    
      
      <img class="portrait mr-3" src="/authors/admin/avatar_hu379968d4a591158aefc150dd1b891ba0_3685589_250x250_fill_q90_lanczos_center.jpg" itemprop="image" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title" itemprop="name"><a href="/authors/admin/">Dr. Craig P. Hutton</a></h5>
      <h6 class="card-subtitle">Data Scientist | Behavioural Neuroscientist</h6>
      
      <ul class="network-icon" aria-hidden="true">
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="/#contact" >
              <i class="fas fa-envelope"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://twitter.com/huttoncp" target="_blank" rel="noopener">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
        
          
          
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://scholar.google.ca/citations?user=bMNjAzkAAAAJ&amp;hl=en" target="_blank" rel="noopener">
              <i class="ai ai-google-scholar"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://github.com/huttoncp" target="_blank" rel="noopener">
              <i class="fab fa-github"></i>
            </a>
          </li>
        
      </ul>
    </div>
  </div>



      
      
      <div class="article-widget">
        <div class="hr-light"></div>
        <h3>Related</h3>
        <ul>
          
          <li><a href="/post/2020-08-29-asgr-2-4-factors/">A Scientist&#39;s Guide to R: Step 2.4 - forcats for factors</a></li>
          
          <li><a href="/post/2020-06-28-asgr-2-3-string-manipulation/">A Scientist&#39;s Guide to R: Step 2.3 - string manipulation and regex</a></li>
          
          <li><a href="/post/2020-03-29-asgr-2-2-joining-data/">A Scientist&#39;s Guide to R: Step 2.2 - Joining Data with dplyr</a></li>
          
          <li><a href="/post/2020-01-25-asgr-2-1-data-transformation-part-2/">A Scientist&#39;s Guide to R: Step 2.1 Data Transformation - part 2</a></li>
          
          <li><a href="/post/2019-12-30-asgr-2-1-data-transformation-part-1/">A Scientist&#39;s Guide to R: Step 2.1. Data Transformation - Part 1</a></li>
          
        </ul>
      </div>
      
    

    

    <div id="disqus_thread"></div>
<script>
(function() {
var d = document, s = d.createElement('script');
s.src = 'https://craig-rbind-io.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

  </div>
</article>

<div class="container">
  <footer class="site-footer">
  
  <p class="powered-by">
    <a href="/privacy/">Privacy Policy</a>
  </p>
  

  <p class="powered-by">
    Copyright © 2020 by Craig P. Hutton &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

</div>


<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

    

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js" integrity="sha256-aYTdUrn6Ow1DDgh5JTc3aDGnnju48y/1c8s1dgkYPQ8=" crossorigin="anonymous"></script>
        
      

      
      
    

    
    

    
    
    
    <script id="dsq-count-scr" src="//craig-rbind-io.disqus.com/count.js" async></script>
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.ee8463f2a394889d45e169a983fe913d.js"></script>

  </body>
</html>


