[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.55.5"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.55.5"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.5"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55.5"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "http://craighutton.netlify.app*"
  to = "https://craig.rbind.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://craighutton.netlify.app*"
  to = "https://craig.rbind.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://craig.rbind.io/*"
  to = "https://craig.rbind.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://craig.netlify.com*"
  to = "https://craig.rbind.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://craighutton.netlify.com*"
  to = "https://craig.rbind.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://craighutton.netlify.com*"
  to = "https://craig.rbind.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://craig.rbind.io/scholar"
  to = "https://scholar.google.ca/citations?user=bMNjAzkAAAAJ&hl=en"
  status = 301
  force = true
  
[[redirects]]
  from = "http://craig.rbind.io/scholar"
  to = "https://scholar.google.ca/citations?user=bMNjAzkAAAAJ&hl=en"
  status = 301
  force = true

[[redirects]]
  from = "craig.rbind.io/scholar"
  to = "https://scholar.google.ca/citations?user=bMNjAzkAAAAJ&hl=en"
  status = 301
  force = true
  
[[redirects]]
  from = "https://craig.rbind.io/talks/bccdc2022"
  to = "https://nexuswebcast.mediasite.com/mediasite/Showcase/bc-cdc-showcase/Presentation/398c028d3f3b458e9d6c37156b3eb13a1d"
  status = 301
  force = true
  
