<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.3.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Dr. Craig P. Hutton">

  
  
  
    
  
  <meta name="description" content="1 TL;DR2 Introduction2.1 load packages2.2 import data3 Factors3.1 factors and data visualization3.2 factors and modelling4 Dates4.1 date/time basics4.2 which day is it?4.3 reading dates4.4 time zones4.5 month names4.6 extracting datetime components4.7 days in a month4.8 custom date formats5 date calculations5.1 correcting excel date-to-numeric conversions6 lubridate for planning a behavioural neuroscience experiment7 Navigation8 Notes1 TL;DRFactors &amp; dates are the other two types of data you’ll encounter on a fairly regular basis.">

  
  <link rel="alternate" hreflang="en-us" href="/post/2020-08-29-asgr-2-4-factors-and-dates/">

  


  

  

  

  

  

  

  
  
  
  <meta name="theme-color" content="#2962ff">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

  

  
  
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700|Roboto:400,400italic,700|Roboto+Mono">
  

  
  
  
  <link rel="stylesheet" href="/css/academic.min.dd3b7994ab53a1ddaf2421ab58c1587f.css">

  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-140167948-1', 'auto');
      ga('set', 'anonymizeIp', true);
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="//www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/2020-08-29-asgr-2-4-factors-and-dates/">

  
  
  
  
    
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@huttoncp">
  <meta property="twitter:creator" content="@huttoncp">
  
  <meta property="og:site_name" content="Craig Hutton, PhD">
  <meta property="og:url" content="/post/2020-08-29-asgr-2-4-factors-and-dates/">
  <meta property="og:title" content="A Scientist&#39;s Guide to R: Step 2.4 - forcats for factors | Craig Hutton, PhD">
  <meta property="og:description" content="1 TL;DR2 Introduction2.1 load packages2.2 import data3 Factors3.1 factors and data visualization3.2 factors and modelling4 Dates4.1 date/time basics4.2 which day is it?4.3 reading dates4.4 time zones4.5 month names4.6 extracting datetime components4.7 days in a month4.8 custom date formats5 date calculations5.1 correcting excel date-to-numeric conversions6 lubridate for planning a behavioural neuroscience experiment7 Navigation8 Notes1 TL;DRFactors &amp; dates are the other two types of data you’ll encounter on a fairly regular basis."><meta property="og:image" content="/post/2020-08-29-asgr-2-4-factors-and-dates/featured.png">
  <meta property="og:locale" content="en-us">
  
  <meta property="article:published_time" content="2020-08-29T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2020-08-29T00:00:00&#43;00:00">
  

  

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
  window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#2962ff",
          "text": "#fff"
        },
        "button": {
          "background": "#fff",
          "text": "#2962ff"
        }
      },
      "theme": "classic",
      "content": {
        "message": "This website uses cookies to ensure you get the best experience on our website.",
        "dismiss": "Got it!",
        "link": "Learn more",
        "href": "/privacy/"
      }
    })});
</script>


  

  <title>A Scientist&#39;s Guide to R: Step 2.4 - forcats for factors | Craig Hutton, PhD</title>

</head>
<body id="top" data-spy="scroll" data-target="#TableOfContents" data-offset="71" >
  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" role="textbox" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>



<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/"><img src="/img/Picture1.png" alt="Craig Hutton, PhD"></a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav mr-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#about">
            
            <span>Home</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#skills">
            
            <span>Skills</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#experience">
            
            <span>Experience</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts">
            
            <span>Posts</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#publications">
            
            <span>Publications</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#accomplishments">
            
            <span>Awards</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact">
            
            <span>Contact</span>
            
          </a>
        </li>

        
        

      
      </ul>
      <ul class="navbar-nav ml-auto">
      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  













<div class="article-header d-xl-none">
  <div class="featured-image" style="background-image: url('/post/2020-08-29-asgr-2-4-factors-and-dates/featured_hu3922ef13c9d2627cf512baf19fc48074_35544_800x0_resize_lanczos_2.png');"></div>
  
</div>


<div class="container-fluid split-header d-none d-xl-block">
  <div class="row">
    <div class="col-6">
      <div class="split-header-content">
        <h1 itemprop="name">A Scientist&#39;s Guide to R: Step 2.4 - forcats for factors</h1>

        

        



<meta content="2020-08-29 00:00:00 &#43;0000 UTC" itemprop="datePublished">
<meta content="2020-08-29 00:00:00 &#43;0000 UTC" itemprop="dateModified">

<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    <time>Aug 29, 2020</time>
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    30 min read
  </span>
  

  
  
  <span class="middot-divider"></span>
  <a href="/post/2020-08-29-asgr-2-4-factors-and-dates/#disqus_thread"></a>
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder"></i>
    <a href="/categories/r/">R</a>, <a href="/categories/reproducible-research/">Reproducible Research</a>, <a href="/categories/data-cleaning-and-transformation/">Data Cleaning and Transformation</a></span>
  

  

</div>


        















        
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=A%20Scientist%27s%20Guide%20to%20R%3a%20Step%202.4%20-%20forcats%20for%20factors&amp;url=%2fpost%2f2020-08-29-asgr-2-4-factors-and-dates%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fpost%2f2020-08-29-asgr-2-4-factors-and-dates%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-facebook-f"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fpost%2f2020-08-29-asgr-2-4-factors-and-dates%2f&amp;title=A%20Scientist%27s%20Guide%20to%20R%3a%20Step%202.4%20-%20forcats%20for%20factors"
         target="_blank" rel="noopener">
        <i class="fab fa-linkedin-in"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fpost%2f2020-08-29-asgr-2-4-factors-and-dates%2f&amp;title=A%20Scientist%27s%20Guide%20to%20R%3a%20Step%202.4%20-%20forcats%20for%20factors"
         target="_blank" rel="noopener">
        <i class="fab fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=A%20Scientist%27s%20Guide%20to%20R%3a%20Step%202.4%20-%20forcats%20for%20factors&amp;body=%2fpost%2f2020-08-29-asgr-2-4-factors-and-dates%2f">
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


      </div>
    </div>
    <div class="col-6">
      <div class="split-header-image">
        <img src="/post/2020-08-29-asgr-2-4-factors-and-dates/featured_hu3922ef13c9d2627cf512baf19fc48074_35544_680x500_fill_q90_lanczos_smart1_2.png" itemprop="image" alt="">
        
      </div>
    </div>
  </div>
</div>

<div class="article-container d-xl-none">
  <h1 itemprop="name">A Scientist&#39;s Guide to R: Step 2.4 - forcats for factors</h1>

  

  



<meta content="2020-08-29 00:00:00 &#43;0000 UTC" itemprop="datePublished">
<meta content="2020-08-29 00:00:00 &#43;0000 UTC" itemprop="dateModified">

<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    <time>Aug 29, 2020</time>
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    30 min read
  </span>
  

  
  
  <span class="middot-divider"></span>
  <a href="/post/2020-08-29-asgr-2-4-factors-and-dates/#disqus_thread"></a>
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder"></i>
    <a href="/categories/r/">R</a>, <a href="/categories/reproducible-research/">Reproducible Research</a>, <a href="/categories/data-cleaning-and-transformation/">Data Cleaning and Transformation</a></span>
  

  
    
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=&amp;url="
         target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u="
         target="_blank" rel="noopener">
        <i class="fab fa-facebook-f"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=&amp;title="
         target="_blank" rel="noopener">
        <i class="fab fa-linkedin-in"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=&amp;title="
         target="_blank" rel="noopener">
        <i class="fab fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=&amp;body=">
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>

  














</div>



  <div class="article-container">

    <div class="article-style" itemprop="articleBody">
      

<div id="TOC">
<ul>
<li><a href="#tldr"><span class="toc-section-number">1</span> <strong>TL;DR</strong></a></li>
<li><a href="#introduction"><span class="toc-section-number">2</span> <strong>Introduction</strong></a><ul>
<li><a href="#load-packages"><span class="toc-section-number">2.1</span> load packages</a></li>
<li><a href="#import-data"><span class="toc-section-number">2.2</span> import data</a></li>
</ul></li>
<li><a href="#factors"><span class="toc-section-number">3</span> <strong>Factors</strong></a><ul>
<li><a href="#factors-and-data-visualization"><span class="toc-section-number">3.1</span> factors and data visualization</a></li>
<li><a href="#factors-and-modelling"><span class="toc-section-number">3.2</span> factors and modelling</a></li>
</ul></li>
<li><a href="#dates"><span class="toc-section-number">4</span> <strong>Dates</strong></a><ul>
<li><a href="#datetime-basics"><span class="toc-section-number">4.1</span> date/time basics</a></li>
<li><a href="#which-day-is-it"><span class="toc-section-number">4.2</span> which day is it?</a></li>
<li><a href="#reading-dates"><span class="toc-section-number">4.3</span> reading dates</a></li>
<li><a href="#time-zones"><span class="toc-section-number">4.4</span> time zones</a></li>
<li><a href="#month-names"><span class="toc-section-number">4.5</span> month names</a></li>
<li><a href="#extracting-datetime-components"><span class="toc-section-number">4.6</span> extracting datetime components</a></li>
<li><a href="#days-in-a-month"><span class="toc-section-number">4.7</span> days in a month</a></li>
<li><a href="#custom-date-formats"><span class="toc-section-number">4.8</span> custom date formats</a></li>
</ul></li>
<li><a href="#date-calculations"><span class="toc-section-number">5</span> date calculations</a><ul>
<li><a href="#correcting-excel-date-to-numeric-conversions"><span class="toc-section-number">5.1</span> correcting excel date-to-numeric conversions</a></li>
</ul></li>
<li><a href="#lubridate-for-planning-a-behavioural-neuroscience-experiment"><span class="toc-section-number">6</span> lubridate for planning a behavioural neuroscience experiment</a></li>
<li><a href="#navigation"><span class="toc-section-number">7</span> Navigation</a></li>
<li><a href="#notes"><span class="toc-section-number">8</span> Notes</a></li>
</ul>
</div>

<div id="tldr" class="section level1">
<h1><span class="header-section-number">1</span> <strong>TL;DR</strong></h1>
<p>Factors &amp; dates are the other two types of data you’ll encounter on a fairly regular basis. This post will show you how to use the <a href="https://forcats.tidyverse.org/">forcats</a> and <a href="https://lubridate.tidyverse.org/">lubridate</a> tidyverse packages in R so you’ll know how to handle factors and dates when you encounter them.</p>
</div>
<div id="introduction" class="section level1">
<h1><span class="header-section-number">2</span> <strong>Introduction</strong></h1>
<p>The 8th post of the <a href="https://craig.rbind.io/post/2019-05-17-asgr-basic-workflow/">Scientist’s Guide to R series</a> covers how to work with dates and factors in R. I decided to cover these two important foundational topics together in this post so that we can confidently move on to more exciting topics sooner (e.g. data exploration).</p>
<p><em>N.B.</em> if anything I’m covering seems strange/confusing to you and you’re jumping into the series now, there’s a good chance I covered it in an earlier post and you should be able to find the relevant section pretty quickly via the search bar that can be accessed via the magnifying glass icon at the top right corner of the page.</p>
<div id="load-packages" class="section level2">
<h2><span class="header-section-number">2.1</span> load packages</h2>
<p>As usual, we’ll start by loading the packages we’ll need.</p>
<pre class="r"><code>library(tidyverse) #note: forcats is installed and loaded with the tidyverse</code></pre>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 4.0.2</code></pre>
<pre class="r"><code>#while it is part of the &quot;tidyverse&quot;, lubridate is installed and loaded
#separately from the tidyverse meta-package

#install.packages(&quot;lubridate&quot;) #uncomment and run if you haven&#39;t installed it before
library(lubridate) </code></pre>
</div>
<div id="import-data" class="section level2">
<h2><span class="header-section-number">2.2</span> import data</h2>
<p>For this post we’ll work with the gapminder data one last time so we can focus on applying new methods to data that we’re already familiar with. I promise we will use something different starting in the next post.</p>
<pre class="r"><code>library(gapminder) #in this case we import the data by loading the gapminder package</code></pre>
<p>A glimpse of the structure of the gapminder data using dplyr’s <code>glimpse()</code> function (loaded with the tidyverse) shows us that there are columns for the country and continent that are already both factors.</p>
<pre class="r"><code>gapminder %&gt;% glimpse() #%&gt;% is the pipe operator (covered in an earlier post)</code></pre>
<pre><code>## Rows: 1,704
## Columns: 6
## $ country   &lt;fct&gt; Afghanistan, Afghanistan, Afghanistan, Afghanistan, Afgha...
## $ continent &lt;fct&gt; Asia, Asia, Asia, Asia, Asia, Asia, Asia, Asia, Asia, Asi...
## $ year      &lt;int&gt; 1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 199...
## $ lifeExp   &lt;dbl&gt; 28.801, 30.332, 31.997, 34.020, 36.088, 38.438, 39.854, 4...
## $ pop       &lt;int&gt; 8425333, 9240934, 10267083, 11537966, 13079460, 14880372,...
## $ gdpPercap &lt;dbl&gt; 779.4453, 820.8530, 853.1007, 836.1971, 739.9811, 786.113...</code></pre>
</div>
</div>
<div id="factors" class="section level1">
<h1><span class="header-section-number">3</span> <strong>Factors</strong></h1>
<p>Factors were briefly introduced in an <a href="https://craig.rbind.io/post/2019-08-06-asgr-2-0-basic-operations-and-data-structures/#factors">earlier post</a> as modifications of character or numeric vectors which enables them to be used as categorical variables AKA nominal variables. Categorical variables take on a few discrete values or levels, e.g. biological sex (levels = Male &amp; Female), or continent (levels = Asia, Africa, North America, South America, Antarctica, Europe, &amp; Australia/Oceania). If you’re doing experimental work, you’ll need to use a factor to represent the variable encoding your experimental conditions or treatment groups.</p>
<p>Recall that a factor can be defined in R using the base R <code>factor()</code> function,</p>
<pre class="r"><code>y &lt;- rep(c(&quot;a&quot;, &quot;b&quot;, &quot;o&quot;), 10) #a vector of the letters a, b, &amp; c repeated 10x as an example 

fruit_category &lt;- factor(x = y, #vector you wish to use to define as a factor 
                levels = c(&quot;a&quot;, &quot;b&quot;, &quot;o&quot;), #what are the unique values/levels of the factor 
                labels = c(&quot;Apples&quot;, &quot;Bananas&quot;, &quot;Oranges&quot;), #use the labels arg to change the labels of the factor levels
                ordered = FALSE) #if you want the factor to be ordered set this to TRUE (i.e. for an ordinal variable)

fruit_category #prints the values of the factor and tells you what the levels of it are</code></pre>
<pre><code>##  [1] Apples  Bananas Oranges Apples  Bananas Oranges Apples  Bananas Oranges
## [10] Apples  Bananas Oranges Apples  Bananas Oranges Apples  Bananas Oranges
## [19] Apples  Bananas Oranges Apples  Bananas Oranges Apples  Bananas Oranges
## [28] Apples  Bananas Oranges
## Levels: Apples Bananas Oranges</code></pre>
<pre class="r"><code>#N.B. if you don&#39;t care about the order of factor levels and are happy with the
#labels, you could instead convert a numeric or character vector to a factor
#using as.factor()</code></pre>
<p>To check the levels of a factor without printing out its values at the same time we can use the base R <code>levels()</code> function (similar to the base R <code>unique()</code> function for other vector types)</p>
<pre class="r"><code>levels(fruit_category)</code></pre>
<pre><code>## [1] &quot;Apples&quot;  &quot;Bananas&quot; &quot;Oranges&quot;</code></pre>
<pre class="r"><code>#this is more useful for the gapminder factors since we didn&#39;t define those
gapminder$continent %&gt;% levels()</code></pre>
<pre><code>## [1] &quot;Africa&quot;   &quot;Americas&quot; &quot;Asia&quot;     &quot;Europe&quot;   &quot;Oceania&quot;</code></pre>
<pre class="r"><code>gapminder$country %&gt;% levels() %&gt;% head(10) #show the 1st 10 levels</code></pre>
<pre><code>##  [1] &quot;Afghanistan&quot; &quot;Albania&quot;     &quot;Algeria&quot;     &quot;Angola&quot;      &quot;Argentina&quot;  
##  [6] &quot;Australia&quot;   &quot;Austria&quot;     &quot;Bahrain&quot;     &quot;Bangladesh&quot;  &quot;Belgium&quot;</code></pre>
<p>You’ll primarily end up using factors in 2 circumstances: when fitting statistical models and plotting data. Although we won’t go into data visualization and modelling in too much detail until later in the series, we’ll get our toes wet here to spice things up a bit.</p>
<div id="factors-and-data-visualization" class="section level2">
<h2><span class="header-section-number">3.1</span> factors and data visualization</h2>
<p>Ignoring the temporal nature of the data for now, let’s say we were interested in looking at the median life expectancy of each continent to see if there were any differences between them.</p>
<p>This can be done most easily using a non-parametric box-and-whisker plot, which shows the 25th percentile and 75th percentile as the bottom and top of the box, the median (i.e. 50th percentile) as a line inside the box, then whiskers extending above and below the box for more extreme values<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> and circles for points beyond the whisker thresholds that may be outliers.</p>
<p>We can generate a box plot in R using the base R boxplot() function. In case you’re wondering, we <em>will</em> cover visualization techniques with the popular ggplot2 package in a future post.</p>
<pre class="r"><code>#base R boxplot
boxplot(lifeExp ~ continent, #formula syntax of the form y-variable ~ x-variable
        data = gapminder)</code></pre>
<p><img src="/post/2020-08-29-ASGR-2-4-factors-and-dates/index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>That’s great, but what if we wanted to reorder the levels of the factor so that the Americas appear first? We could redefine the continent factor using the <code>factor()</code> function, or we could use <code>fct_relevel()</code> from the forcats package (in conjunction with <a href="https://craig.rbind.io/post/2019-12-30-asgr-2-1-data-transformation-part-1/#mutate">dplyr::mutate()</a>).</p>
<pre class="r"><code>#if we use factor() we need to specify all levels again
p1a &lt;- gapminder %&gt;%
  #first modify the column using dplyr::mutate(), which was loaded with
  #library(tidyverse)
  mutate(continent = factor(continent, 
                            levels = c(&quot;Americas&quot;, &quot;Africa&quot;, &quot;Asia&quot;, &quot;Europe&quot;, &quot;Oceania&quot;)) 
  ) %&gt;%
  #recall that &quot;.&quot; is used to specify which argument the output from whatever
  #was before the %&gt;% (pipe operator) should be passed to
  boxplot(lifeExp ~ continent, data = .) 

#for fct_relevel you only need to mention the levels you want to rearrange
p1b &lt;- gapminder %&gt;%
  mutate(continent = fct_relevel(continent, &quot;Americas&quot;) 
         #by default levels you mention move to the front
  ) %&gt;%
  boxplot(lifeExp ~ continent, data = .) </code></pre>
<p><img src="/post/2020-08-29-ASGR-2-4-factors-and-dates/index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>identical(p1a, p1b)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>#both options have the same effect on the plot


#if we wanted to move the data for the Americas to the end, we could use the
#&quot;after&quot; argument
gapminder %&gt;%
  mutate(continent = fct_relevel(continent, &quot;Americas&quot;,
                                 after = Inf) 
         #here the special character set &quot;Inf&quot; specifies the end
         ) %&gt;%
  boxplot(lifeExp ~ continent, data = .) </code></pre>
<p><img src="/post/2020-08-29-ASGR-2-4-factors-and-dates/index_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<pre class="r"><code>#or to the 4th position
gapminder %&gt;%
  mutate(continent = fct_relevel(continent, &quot;Americas&quot;,
                                 after = 3) 
         ) %&gt;%
  boxplot(lifeExp ~ continent, data = .) </code></pre>
<p><img src="/post/2020-08-29-ASGR-2-4-factors-and-dates/index_files/figure-html/unnamed-chunk-7-3.png" width="672" /></p>
<p>In addition to manually reordering the levels of a factor using <code>fct_relevel()</code>, you can reorder a factor based on another variable, e.g. if you want them to appear in order of ascending life expectancy:</p>
<pre class="r"><code>gapminder %&gt;%
  mutate(continent = fct_reorder(continent, lifeExp) 
         ) %&gt;%
  boxplot(lifeExp ~ continent, data = .) </code></pre>
<p><img src="/post/2020-08-29-ASGR-2-4-factors-and-dates/index_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>#to sort in descending order add .desc = TRUE in the fct_reorder call.
gapminder %&gt;%
  mutate(continent = fct_reorder(continent, lifeExp, 
                                 .desc = TRUE)  
         ) %&gt;%
  boxplot(lifeExp ~ continent, data = .) </code></pre>
<p><img src="/post/2020-08-29-ASGR-2-4-factors-and-dates/index_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<p>To modify the values of a factor you can use either the labels argument of the base R <code>factor()</code> function and (again) have to specify all values and labels, which can become tedious really fast, or you can just <code>forcats::fct_recode()</code>. For example, let’s say we wanted to change continent values of “Oceania” to “Australia”:</p>
<pre class="r"><code>#base R&#39;s factor()
gapminder %&gt;%
  mutate(continent = factor(continent,  
                            #all existing unique values/levels you want to use need to be specified
                            levels = c(&quot;Africa&quot;, &quot;Americas&quot;, &quot;Asia&quot;, &quot;Europe&quot;, &quot;Oceania&quot;),
                            #one label per level needs to be specified, in the same order as the levels
                            labels = c(&quot;Africa&quot;, &quot;Americas&quot;, &quot;Asia&quot;, &quot;Europe&quot;, &quot;Australia&quot;))
         ) %&gt;%
  boxplot(lifeExp ~ continent, data = .) 

#using forcats::fct_recode()
gapminder %&gt;%
  mutate(continent = fct_recode(continent,
                                #only the value(s) you want to recode need to be specified
                                &quot;Australia&quot; = &quot;Oceania&quot;) #&quot;new value&quot; = &quot;old value&quot;
         ) %&gt;%
  boxplot(lifeExp ~ continent, data = .) </code></pre>
<p><img src="/post/2020-08-29-ASGR-2-4-factors-and-dates/index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Forcats also makes it easy to aggregate levels using <code>fct_recode()</code> or <code>fct_lump()</code>. The main difference is that <code>fct_recode()</code> is for manually recoding, while <code>fct_lump()</code> will combine categories based on a criterion like those with counts less than a specified threshold.</p>
<p>For example, if we wanted to view the combined data for Europe and Asia under the label “Eurasia”, we could do so using <code>fct_recode()</code>:</p>
<pre class="r"><code>gapminder %&gt;%
  mutate(continent = fct_recode(continent,
                                #use the same label for more than one value to aggregate
                                &quot;Eurasia&quot; = &quot;Europe&quot;,
                                &quot;Eurasia&quot; = &quot;Asia&quot;) 
         ) %&gt;%
  boxplot(lifeExp ~ continent, data = .) 

#a shortcut for this use of fct_recode() is fct_collapse()
gapminder %&gt;%
  mutate(continent = fct_collapse(continent,
                                &quot;Eurasia&quot; = c(&quot;Europe&quot;, &quot;Asia&quot;)) 
         ) %&gt;%
  boxplot(lifeExp ~ continent, data = .) </code></pre>
<p><img src="/post/2020-08-29-ASGR-2-4-factors-and-dates/index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Or if we wanted to aggregate the data for the continents other than the top 2 most common values we could use <code>fct_lump_n()</code>:</p>
<pre class="r"><code>gapminder %&gt;%
  mutate(continent = fct_lump_n(continent, 
                                #the n argument determines the number of levels to
                                #retain (in order of descending frequency of
                                #appearance)
                                n = 2,
                                #the other_level argument is used to set the label
                                #for the new category representing the former
                                #uncommon categories
                                other_level = &quot;Other&quot; #default label is &quot;Other&quot;
  )  
  ) %&gt;%
  boxplot(lifeExp ~ continent, data = .) </code></pre>
<p><img src="/post/2020-08-29-ASGR-2-4-factors-and-dates/index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>#or to lump together categories appearing less than a minimum number of times,
#use fct_lump_min()

gapminder %&gt;%
  mutate(continent = fct_lump_min(continent, 
                                  #the min argument defines the minimum
                                  #frequency threshold for a category to avoid
                                  #being lumped together. For this demo we&#39;ll
                                  #use the mean count of each continent using
                                  #the mean() and table() functions and lump together
                                  #continents appearing less often than that
                                  min = mean(table(gapminder$continent)))    
  ) %&gt;%
  boxplot(lifeExp ~ continent, data = .) </code></pre>
<p><img src="/post/2020-08-29-ASGR-2-4-factors-and-dates/index_files/figure-html/unnamed-chunk-11-2.png" width="672" /></p>
<p>There are a few other <code>fct_lump_*</code> variants that you can learn about in the <code>fct_lump()</code> documentation.</p>
<p>To drop unused levels of a factor you can use <code>fct_drop()</code></p>
<pre class="r"><code>#say we have a factor with more levels than appear in the data

y &lt;- rep(c(&quot;a&quot;, &quot;b&quot;, &quot;o&quot;), 10) #a vector of the letters a, b, &amp; c repeated 10x as an example 

fruit_category &lt;- factor(x = y, 
                levels = c(&quot;a&quot;, &quot;b&quot;, &quot;o&quot;, &quot;p&quot;), 
                labels = c(&quot;Apples&quot;, &quot;Bananas&quot;, &quot;Oranges&quot;, &quot;Pineapple&quot;))

fruit_category</code></pre>
<pre><code>##  [1] Apples  Bananas Oranges Apples  Bananas Oranges Apples  Bananas Oranges
## [10] Apples  Bananas Oranges Apples  Bananas Oranges Apples  Bananas Oranges
## [19] Apples  Bananas Oranges Apples  Bananas Oranges Apples  Bananas Oranges
## [28] Apples  Bananas Oranges
## Levels: Apples Bananas Oranges Pineapple</code></pre>
<pre class="r"><code>#pineapple is listed as a level but there are no entries for it!

#oops, we forgot that &quot;p&quot; for &quot;pinapple&quot; wasn&#39;t included in this vector

#drop it!
fruit_category &lt;- fct_drop(fruit_category)

levels(fruit_category)</code></pre>
<pre><code>## [1] &quot;Apples&quot;  &quot;Bananas&quot; &quot;Oranges&quot;</code></pre>
</div>
<div id="factors-and-modelling" class="section level2">
<h2><span class="header-section-number">3.2</span> factors and modelling</h2>
<p>To see how factor levels affect modelling, lets fit a basic linear regression model to see if life expectancy is differs between continents using the base R <code>lm()</code> &amp; <code>summary()</code> functions.</p>
<pre class="r"><code>#fit the model
linear_regression_model &lt;- lm(lifeExp ~ continent, 
                              data = gapminder)

#print the model results summary using the summary() function
summary(linear_regression_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lifeExp ~ continent, data = gapminder)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -31.2639  -5.4537   0.3297   6.0480  27.5767 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        48.8653     0.3696  132.22   &lt;2e-16 ***
## continentAmericas  15.7934     0.6486   24.35   &lt;2e-16 ***
## continentAsia      11.1996     0.5931   18.88   &lt;2e-16 ***
## continentEurope    23.0384     0.6110   37.70   &lt;2e-16 ***
## continentOceania   25.4609     1.9204   13.26   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.232 on 1699 degrees of freedom
## Multiple R-squared:  0.4904, Adjusted R-squared:  0.4892 
## F-statistic: 408.7 on 4 and 1699 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Ignoring most of the output for now (which will be covered in detail in a future post on modelling in R), we can see a set of t-tests for each level of the continent factor except for Africa. This is because when an lm() object is passed to the summary() function, R evaluates linear regression predictor variables that are factors by comparing each category to a baseline/reference category, which happens to be “Africa” in this case. If the assumptions of the linear regression model are valid, this output tells us if the life expectancy (what we’ve specified as the dependent variable) of each non-African continent is statistically equivalent or not (b/c in frequentist stats we’re evaluating a null hypothesis of equivalence) compared to the life expectancy of Africa.</p>
<p>What if you wanted to compare each continent to the Americas instead? Just relevel the continent factor and make Americas the first level.</p>
<pre class="r"><code>#fit the model
linear_regression_model &lt;- lm(lifeExp ~ continent, 
                              data = gapminder %&gt;% 
                                mutate(continent = 
                                         fct_relevel(continent,
                                                     #make Americas the new &quot;reference&quot; level
                                                     &quot;Americas&quot;))
                              )

#print the model results summary using the summary() function
summary(linear_regression_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lifeExp ~ continent, data = gapminder %&gt;% mutate(continent = fct_relevel(continent, 
##     &quot;Americas&quot;)))
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -31.2639  -5.4537   0.3297   6.0480  27.5767 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       64.6587     0.5330 121.309  &lt; 2e-16 ***
## continentAfrica  -15.7934     0.6486 -24.350  &lt; 2e-16 ***
## continentAsia     -4.5938     0.7066  -6.501 1.05e-10 ***
## continentEurope    7.2449     0.7217  10.039  &lt; 2e-16 ***
## continentOceania   9.6675     1.9584   4.936 8.74e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.232 on 1699 degrees of freedom
## Multiple R-squared:  0.4904, Adjusted R-squared:  0.4892 
## F-statistic: 408.7 on 4 and 1699 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Now the life expectancy of each non-American continent is being compared to the life expectancy of the Americas.</p>
<p>BTW, in case you were wondering, we will cover how to get the usual ANOVA outputs for linear models that you may be more accustomed to seeing in a later post.</p>
<p>Now you know the basics of the forcats package which should help you work with factors in R.</p>
</div>
</div>
<div id="dates" class="section level1">
<h1><span class="header-section-number">4</span> <strong>Dates</strong></h1>
<p>Until I learned aboout the lubridate package, dates were one of the most frustrating data structures to work. This is partly because there are many different formats that can be used to specify them and it’s not uncommon for multiple formats to be used within the same dataset if more than one person was entering the data. To make things worse, when you import data from Excel, often dates will be read as 5-digit numbers that can leave you wondering if the data somehow became corrupted.</p>
<p>This section of the post will show you how lubridate can help you overcome these sorts of problems. Afterwards I’ll also show you an example of how using lubridate can help you with the scheduling part of planning a research study.</p>
<div id="datetime-basics" class="section level2">
<h2><span class="header-section-number">4.1</span> date/time basics</h2>
<p>In R, temporal data can be represented as dates, times (within a day), or a combination of a date and a time (date-time). If your data is stored as a tibble, these types will have different class labels: “date”, “time” and “dttm” respectively. Otherwise, e.g. as a vector or a column of a data frame, they’ll be classified using a date/time format called <a href="https://www.stat.berkeley.edu/~s133/dates.html">“POSIXct”</a> (stands for <strong>p</strong>ortable <strong>o</strong>perating <strong>s</strong>ystem <strong>i</strong>nterface [originally designed for UNI<strong>X</strong>], <strong>c</strong>hronological <strong>t</strong>ime). There is also a “local time” version which has to do with time zones, but we won’t worry about it for now. Each of these date/time object types has a slighlty different default display format (“default” because lubridate allows you to modify it) that determines how the values are displayed:</p>
<ul>
<li><p>dates: yyyy-mm-dd (year-month-day)</p></li>
<li><p>times: hh:mm:ss (hours:minutes:seconds)</p></li>
<li><p>datetime: yyyy-mm-dd hh:mm:ss</p></li>
</ul>
<p>Under the hood, a date object in R is stored as the number of days from January 1st of 1970, which is revealed if you convert a date to a numeric vector.</p>
<pre class="r"><code>as.Date(&quot;1970-01-01&quot;) %&gt;% 
  as.numeric()</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>as.Date(&quot;1970-01-02&quot;) %&gt;% 
  as.numeric()</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>as.Date(&quot;2020-08-29&quot;) %&gt;% 
  as.numeric()</code></pre>
<pre><code>## [1] 18503</code></pre>
<p>Wow, it’s been a lot of days since January 1st of 1970.</p>
<p>Why does R represent dates internally as integers? So you can do calculations with them, e.g. to get the date 100 days from August 29th, 2020 (the day I am wrote this):</p>
<pre class="r"><code>as.Date(&quot;2020-08-29&quot;) + 100</code></pre>
<pre><code>## [1] &quot;2020-12-07&quot;</code></pre>
<p>calculating the number of days between 2 dates is also pretty straightforward, just subtract the earlier one from the later one:</p>
<pre class="r"><code>as.Date(&quot;2020-08-29&quot;) - as.Date(&quot;2020-01-01&quot;)</code></pre>
<pre><code>## Time difference of 241 days</code></pre>
</div>
<div id="which-day-is-it" class="section level2">
<h2><span class="header-section-number">4.2</span> which day is it?</h2>
<p>In base R, you can also get today’s date using <code>Sys.Date()</code></p>
<pre class="r"><code>Sys.Date()</code></pre>
<pre><code>## [1] &quot;2020-08-29&quot;</code></pre>
<p>Or using the easier to remember lubidate function <code>today()</code></p>
<pre class="r"><code>today()</code></pre>
<pre><code>## [1] &quot;2020-08-29&quot;</code></pre>
<p>You can also get the current system date &amp; time using <code>base::Sys.time()</code> or <code>lubridate::now()</code></p>
<pre class="r"><code>Sys.time()</code></pre>
<pre><code>## [1] &quot;2020-08-29 15:28:58 PDT&quot;</code></pre>
<pre class="r"><code>now()</code></pre>
<pre><code>## [1] &quot;2020-08-29 15:28:58 PDT&quot;</code></pre>
</div>
<div id="reading-dates" class="section level2">
<h2><span class="header-section-number">4.3</span> reading dates</h2>
<p>While we didn’t have any trouble turning a string into a date when it was presented in the standard format “yyyy-mm-dd”, things go awry if we try the same thing with a non-standard format like “dd-mm-yyyy”:</p>
<pre class="r"><code>as.Date(&quot;29-08-2020&quot;) %&gt;% as.numeric()</code></pre>
<pre><code>## [1] -708704</code></pre>
<p>Well that doesn’t look right!</p>
<p>TO use a non-standard format with as.Date() we’ll need to specify it with the <code>format</code> argument via a combination of case-sensitive <code>%*</code> (replace * with the appropriate letter) codes of the form <code>"%Y-%m-%d"</code>, where the most common ones you may need are:</p>
<ul>
<li><p><code>%a</code> = abbreviated weekday name</p></li>
<li><p><code>%A</code> = full weekday name</p></li>
<li><p><code>%b</code> = abbreviated month name</p></li>
<li><p><code>%B</code> = full month name</p></li>
<li><p><code>%d</code> = day of the month as a 2-digit number</p></li>
<li><p><code>%D</code> = shortcut for <code>%Y/%m/%d</code></p></li>
<li><p><code>%e</code> = day of the month as a single digit number with a leading space</p></li>
<li><p><code>%H</code> or <code>%I</code> = hours as a 2-digit number</p></li>
<li><p><code>%j</code> = day of the year as a 3-digit number</p></li>
<li><p><code>%m</code> = month as a 2-digit number</p></li>
<li><p><code>%M</code> = Minute as a 2-digit number</p></li>
<li><p><code>%p</code> = AM/PM indicator to use in conjuction with hours specified via <code>%I</code> but not <code>%H</code></p></li>
<li><p><code>%S</code> = seconds as a 2-digit number</p></li>
<li><p><code>%U</code> = week of the year as a 2-digit number (using Sunday as day 1 of the week)</p></li>
<li><p><code>%T</code> = shortcut for <code>%H:%M:%S</code></p></li>
<li><p><code>%y</code> = year without the century (2-digits)</p></li>
<li><p><code>%Y</code> = year with the century</p></li>
<li><p><code>%Z</code> = time zone abbreviation as a character string</p></li>
</ul>
<p>See the strptime help documentation for more information on these codes and a complete list using <code>?strptime</code></p>
<p>To correctly parse “29-08-2020” as day-month-year using as.Date() we would therefore need to specify the format as follows:</p>
<pre class="r"><code>dt &lt;- as.Date(&quot;29-08-2020&quot;, format = &quot;%d-%m-%Y&quot;)

dt </code></pre>
<pre><code>## [1] &quot;2020-08-29&quot;</code></pre>
<pre class="r"><code>dt %&gt;% as.numeric()</code></pre>
<pre><code>## [1] 18503</code></pre>
<p>Now it shows up the way we expected, and is correctly represented internally as 18,503 days since January 1st of 1970 (as before) rather than -708,704.</p>
<p>As you can see, this could make date processing quite tedious, especially if you don’t work with dates or times very often or if your data use multiple formats! This is an example of the kinds of hassle that lubridate was created to help us overcome. Instead of having to specify the format using <code>%*</code>-codes, lubridate has a set of functions that make it easy to read dates in various string formats that you may encounter in raw data and convert them to the standard format</p>
<ul>
<li><p><code>ymd()</code> for strings with the year then the month then the day</p></li>
<li><p><code>dmy()</code> day month year</p></li>
<li><p><code>mdy()</code> month, day, year</p></li>
</ul>
<p>and so on…</p>
<p>These parsing functions make it quite easy to read dates, e.g.</p>
<pre class="r"><code>identical(
  ymd(&quot;2020-08-29&quot;), 
  dmy(&quot;29-08-2020&quot;)
  )</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>identical(
  ymd(&quot;2020-08-29&quot;), 
  mdy(&quot;29-08-2020&quot;)
  )</code></pre>
<pre><code>## Warning: All formats failed to parse. No formats found.</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>If you also need to specify the time, there are extensions for the above convenience functions to make that easy too. Add <code>_h</code> for hours, <code>_hm</code> for hours &amp; minutes, and <code>_hms</code> for hours, minutes, and seconds, e.g.:</p>
<pre class="r"><code>ymd_h(&quot;2020-08-29 22&quot;)</code></pre>
<pre><code>## [1] &quot;2020-08-29 22:00:00 UTC&quot;</code></pre>
<pre class="r"><code>dmy_hm(&quot;29-08-2020 22:09&quot;)</code></pre>
<pre><code>## [1] &quot;2020-08-29 22:09:00 UTC&quot;</code></pre>
<pre class="r"><code>mdy_hms(&quot;08-29-2020 22:09:19&quot;)</code></pre>
<pre><code>## [1] &quot;2020-08-29 22:09:19 UTC&quot;</code></pre>
<p>Since working with datetimes is considerably easier in lubridate than base R, for the sake of brevity I’ll focus on the lubridate approach for most of the remainder of this post. If you would like to learn more about working with datetimes in base R, see <a href="https://www.stat.berkeley.edu/~s133/dates.html">this link</a>.</p>
<p>Fortunately these lubridate functions can also handle a variety of non-numeric characters between the datetime values and still parse them correctly</p>
<pre class="r"><code>ymd(&quot;2020-08-29&quot;) == ymd(&quot;2020/08/29&quot;) </code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>ymd(&quot;2020-08-29&quot;) == ymd(&quot;2020 08 29&quot;)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>ymd(&quot;2020-08-29&quot;) ==  ymd(&quot;2020:08:29&quot;)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>ymd(&quot;2020-08-29&quot;) ==  ymd(&quot;2020$08$29&quot;)</code></pre>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="time-zones" class="section level2">
<h2><span class="header-section-number">4.4</span> time zones</h2>
<p>To specify the time zone we can use the <code>tz</code> argument:</p>
<pre class="r"><code>ymd_h(&quot;2020-08-29 9&quot;, 
      tz = &quot;America/Vancouver&quot;) # tz = Continent/City</code></pre>
<pre><code>## [1] &quot;2020-08-29 09:00:00 PDT&quot;</code></pre>
<p>For example, you could use this to figure out what the time difference is between New York and London or Vancouver and Cairo</p>
<pre class="r"><code>ymd_h(&quot;2020-08-29 9&quot;, tz = &quot;America/New_York&quot;) - ymd_h(&quot;2020-08-29 9&quot;, tz = &quot;Europe/London&quot;)  </code></pre>
<pre><code>## Time difference of 5 hours</code></pre>
<pre class="r"><code>ymd_h(&quot;2020-08-29 9&quot;, tz = &quot;America/Vancouver&quot;) - ymd_h(&quot;2020-08-29 9&quot;, tz = &quot;Africa/Cairo&quot;)  </code></pre>
<pre><code>## Time difference of 9 hours</code></pre>
<p>A list of time zone names can be found on <a href="https://en.wikipedia.org/wiki/List_of_tz_database_time_zones">this wikipedia page</a>.</p>
</div>
<div id="month-names" class="section level2">
<h2><span class="header-section-number">4.5</span> month names</h2>
<p>Lubridate functions can even parse the month names if they’re provided instead of a fully numeric date string.</p>
<pre class="r"><code>mdy(&quot;October 31st, 2020&quot;)</code></pre>
<pre><code>## [1] &quot;2020-10-31&quot;</code></pre>
<pre class="r"><code>dmy(&quot;the 1st of December 2011&quot;)</code></pre>
<pre><code>## [1] &quot;2011-12-01&quot;</code></pre>
</div>
<div id="extracting-datetime-components" class="section level2">
<h2><span class="header-section-number">4.6</span> extracting datetime components</h2>
<p>lubridate also provides a number of self-explanatory functions for extracting some of the information from a date or datetime:</p>
<pre class="r"><code>dt &lt;- ymd_hms(&quot;2020-08-29 22:09:19&quot;)

year(dt)</code></pre>
<pre><code>## [1] 2020</code></pre>
<pre class="r"><code>month(dt)</code></pre>
<pre><code>## [1] 8</code></pre>
<pre class="r"><code>day(dt)</code></pre>
<pre><code>## [1] 29</code></pre>
<pre class="r"><code>hour(dt)</code></pre>
<pre><code>## [1] 22</code></pre>
<pre class="r"><code>minute(dt)</code></pre>
<pre><code>## [1] 9</code></pre>
<pre class="r"><code>second(dt)</code></pre>
<pre><code>## [1] 19</code></pre>
<pre class="r"><code>week(dt) #week of the year</code></pre>
<pre><code>## [1] 35</code></pre>
<pre class="r"><code>wday(dt) #day of the week, numeric</code></pre>
<pre><code>## [1] 7</code></pre>
<pre class="r"><code>wday(dt,#day of the week
     label = TRUE, #as a factor level
     abbr = FALSE) #not abbreviated</code></pre>
<pre><code>## [1] Saturday
## 7 Levels: Sunday &lt; Monday &lt; Tuesday &lt; Wednesday &lt; Thursday &lt; ... &lt; Saturday</code></pre>
<pre class="r"><code>#day of the month, this one isn&#39;t really useful since it gives you the same
#thing as day()
mday(dt) </code></pre>
<pre><code>## [1] 29</code></pre>
<pre class="r"><code>yday(dt) #day of the year</code></pre>
<pre><code>## [1] 242</code></pre>
</div>
<div id="days-in-a-month" class="section level2">
<h2><span class="header-section-number">4.7</span> days in a month</h2>
<p>There is also a lubridate function that tells you how many days there are in a specified month if you haven’t yet memorized them all.</p>
<pre class="r"><code>days_in_month(dt) #the month specified in a datetime object</code></pre>
<pre><code>## Aug 
##  31</code></pre>
<pre class="r"><code>days_in_month(3) #or whichever month you want to specify</code></pre>
<pre><code>## Mar 
##  31</code></pre>
<pre class="r"><code>days_in_month(1:12) #or all months at once</code></pre>
<pre><code>## Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec 
##  31  28  31  30  31  30  31  31  30  31  30  31</code></pre>
</div>
<div id="custom-date-formats" class="section level2">
<h2><span class="header-section-number">4.8</span> custom date formats</h2>
<p>If you’d prefer to have dates displayed differently from the standard/default yyyy-mm-dd format, you can specify an alternative format to use with the <code>lubridate::stamp_date()</code> function. This could be useful if you want the dates to follow a specific format that is used in your lab or workplace.</p>
<pre class="r"><code>#step 1: specify the format using an arbitrary date with stamp_date()
my_stamp &lt;- stamp_date(&quot;January 7th, 2019&quot;) 

#step 2: apply the format to a date object
my_stamp(dt)</code></pre>
<pre><code>## [1] &quot;August 29th, 2020&quot;</code></pre>
<pre class="r"><code>#if there are multiple possibilities lubridate will use the most probable/common one</code></pre>
<p>The alternative way of changing the display format is to apply the base R <code>format()</code> function to a datetime object and specify the format using the <code>%</code>-codes, e.g.</p>
<pre class="r"><code>format(dt, &quot;%B %dth, %Y&quot;)</code></pre>
<pre><code>## [1] &quot;August 29th, 2020&quot;</code></pre>
<p>Again, the lubridate version is a bit easier.</p>
</div>
</div>
<div id="date-calculations" class="section level1">
<h1><span class="header-section-number">5</span> date calculations</h1>
<p>You can add days to a date that’s been processed using lubridate just as easily as we did using the base R as.Date() function</p>
<pre class="r"><code>dt &lt;- ymd(&quot;2020/08/30&quot;)

dt + 10</code></pre>
<pre><code>## [1] &quot;2020-09-09&quot;</code></pre>
<p>A raw number added to a date is interpreted as a request to add the smallest unit of time to the object that is already represented in it. You could instead specify the unit to add (weeks, month, years, etc) to a date with some intuitively-named lubridate helper functions:</p>
<pre class="r"><code>ymd(&quot;2020/08/30&quot;) + 10 #adds 10 days</code></pre>
<pre><code>## [1] &quot;2020-09-09&quot;</code></pre>
<pre class="r"><code>ymd_hms(&quot;2020/08/30 10:12:58&quot;) + 10 #adds 10 seconds</code></pre>
<pre><code>## [1] &quot;2020-08-30 10:13:08 UTC&quot;</code></pre>
<pre class="r"><code>ymd_hms(&quot;2020/08/30 10:12:58&quot;) + days(10) #adds 10 days instead of seconds</code></pre>
<pre><code>## [1] &quot;2020-09-09 10:12:58 UTC&quot;</code></pre>
<pre class="r"><code>ymd(&quot;2020/08/30&quot;) + weeks(1) #adds 1 week</code></pre>
<pre><code>## [1] &quot;2020-09-06&quot;</code></pre>
<pre class="r"><code>ymd(&quot;2020/08/30&quot;) - months(100) #subtracts 100 months</code></pre>
<pre><code>## [1] &quot;2012-04-30&quot;</code></pre>
<pre class="r"><code>ymd(&quot;2020/08/30&quot;) + years(80) #adds 80 years</code></pre>
<pre><code>## [1] &quot;2100-08-30&quot;</code></pre>
<p>You can also add vectors of set intervals. For example, if you had a weekly meeting for the next 10 weeks and wanted to know the dates of each of them, you could use:</p>
<pre class="r"><code>ymd(&quot;2020/08/30&quot;) + 
  weeks(1)*c(1:10) #1 week unit for the interval * vector of meeting indices/values</code></pre>
<pre><code>##  [1] &quot;2020-09-06&quot; &quot;2020-09-13&quot; &quot;2020-09-20&quot; &quot;2020-09-27&quot; &quot;2020-10-04&quot;
##  [6] &quot;2020-10-11&quot; &quot;2020-10-18&quot; &quot;2020-10-25&quot; &quot;2020-11-01&quot; &quot;2020-11-08&quot;</code></pre>
<pre class="r"><code>#if you were given a vector of dates and wanted to know which days of the week
#they fell on you can easily get that too. e.g. if you had a meeting on the 15th
#of every month...
meeting_dates &lt;- ydm(
  stringr::str_c(&quot;2020-15-&quot;, 1:12)
) 

meeting_dates</code></pre>
<pre><code>##  [1] &quot;2020-01-15&quot; &quot;2020-02-15&quot; &quot;2020-03-15&quot; &quot;2020-04-15&quot; &quot;2020-05-15&quot;
##  [6] &quot;2020-06-15&quot; &quot;2020-07-15&quot; &quot;2020-08-15&quot; &quot;2020-09-15&quot; &quot;2020-10-15&quot;
## [11] &quot;2020-11-15&quot; &quot;2020-12-15&quot;</code></pre>
<pre class="r"><code>meeting_dates %&gt;% wday(label = TRUE)</code></pre>
<pre><code>##  [1] Wed Sat Sun Wed Fri Mon Wed Sat Tue Thu Sun Tue
## Levels: Sun &lt; Mon &lt; Tue &lt; Wed &lt; Thu &lt; Fri &lt; Sat</code></pre>
<pre class="r"><code>#or you could apply a date_stamp to them, which could be useful for populating
#an excel report or data collection sheet.
my_stamp &lt;- stamp_date(&quot;Monday, January 7th, 2019&quot;) 

meeting_dates %&gt;% my_stamp()</code></pre>
<pre><code>##  [1] &quot;Wednesday, January 15th, 2020&quot; &quot;Saturday, February 15th, 2020&quot;
##  [3] &quot;Sunday, March 15th, 2020&quot;      &quot;Wednesday, April 15th, 2020&quot;  
##  [5] &quot;Friday, May 15th, 2020&quot;        &quot;Monday, June 15th, 2020&quot;      
##  [7] &quot;Wednesday, July 15th, 2020&quot;    &quot;Saturday, August 15th, 2020&quot;  
##  [9] &quot;Tuesday, September 15th, 2020&quot; &quot;Thursday, October 15th, 2020&quot; 
## [11] &quot;Sunday, November 15th, 2020&quot;   &quot;Tuesday, December 15th, 2020&quot;</code></pre>
<p>You can also get the interval between two dates in the unit(s) of your choice using the <code>lubridate::interval()</code> &amp; <code>lubridate::time_length()</code> functions together</p>
<pre class="r"><code>#step 1: define an interval using lubridate::interval()
int &lt;- interval(mdy(&quot;12-01-2005&quot;), today())

#step 2: use time_length(interval) and the &quot;unit&quot; argument
time_length(int, unit = &quot;day&quot;) #interval length in days</code></pre>
<pre><code>## [1] 5386</code></pre>
<pre class="r"><code>time_length(int, unit = &quot;month&quot;) #interval length in months</code></pre>
<pre><code>## [1] 176.9355</code></pre>
<pre class="r"><code>time_length(int, unit = &quot;year&quot;) #interval length in years</code></pre>
<pre><code>## [1] 14.7459</code></pre>
<pre class="r"><code>time_length(int, unit = c(&quot;day&quot;, &quot;week&quot;, &quot;month&quot;, &quot;year&quot;)) #you can also ask for multiple formats at once</code></pre>
<pre><code>## Warning in if (unit %in% c(&quot;year&quot;, &quot;month&quot;)) {: the condition has length &gt; 1 and
## only the first element will be used</code></pre>
<pre><code>## [1] 5386.00000  769.42857  176.95277   14.74606</code></pre>
<pre class="r"><code>interval(ymd_h(&quot;2020-08-27 10&quot;), now()) %&gt;% 
  time_length(unit = &quot;hour&quot;) #interval length in hours</code></pre>
<pre><code>## [1] 80.86524</code></pre>
<pre class="r"><code>#of course you can also get the difference in days by just subtracting one date
#from the other as we did earlier using base R functions
mdy(&quot;12-10-2005&quot;) - mdy(&quot;12-01-2005&quot;)</code></pre>
<pre><code>## Time difference of 9 days</code></pre>
<div id="correcting-excel-date-to-numeric-conversions" class="section level2">
<h2><span class="header-section-number">5.1</span> correcting excel date-to-numeric conversions</h2>
<p>Although it isn’t part of lubridate, there is a function from the <a href="http://sfirke.github.io/janitor/index.html">janitor</a> package called <code>excel_numeric_to_date()</code> that can help. For example, May 20th of 2016 may have looked like “2016-05-20” in the .xlsx file when you looked at it, but then when it gets imported into R, it appears as the mysterious number 42510 instead. This is an unfortunate issue that sometimes occurs when trying to read data from excel files specifically. The <code>excel_numeric_to_date()</code> simply converts these 5-digit date codes back to the string date format you were expecting.</p>
<pre class="r"><code>janitor::excel_numeric_to_date(42510)</code></pre>
<pre><code>## [1] &quot;2016-05-20&quot;</code></pre>
<pre class="r"><code>#also works with vectors
janitor::excel_numeric_to_date(
  c(42510:42520)
)</code></pre>
<pre><code>##  [1] &quot;2016-05-20&quot; &quot;2016-05-21&quot; &quot;2016-05-22&quot; &quot;2016-05-23&quot; &quot;2016-05-24&quot;
##  [6] &quot;2016-05-25&quot; &quot;2016-05-26&quot; &quot;2016-05-27&quot; &quot;2016-05-28&quot; &quot;2016-05-29&quot;
## [11] &quot;2016-05-30&quot;</code></pre>
</div>
</div>
<div id="lubridate-for-planning-a-behavioural-neuroscience-experiment" class="section level1">
<h1><span class="header-section-number">6</span> lubridate for planning a behavioural neuroscience experiment</h1>
<p>Before I transitioned to working as a data scientist for the BC Government I spent some time doing behavioural neuroscience research. One of the first things I needed to do to conduct an experiment was figure out when I needed to do different things in the lab. I used R to make this process easier and help sort out which days I would need to reserve lab equipment and other resources.</p>
<p>I started by defining some key parameters such as the sample size per group and the number of treatment conditions I planned to use in my design. These parameters mattered because they would determine how many days some aspects of the experiment would take.</p>
<p>For this demo, we’ll plan an experiment with rats that uses an aerobic exercise intervention (for half of the animals, selected at random) that lasts 4 weeks, followed by 7 days of behavioural testing in the Barnes Maze test of spatial learning and memory, and then ex vivo electrophysiological slice recordings to see if we can pickup any changes in neural signalling that might be related to behavioural effects of the exercise intervention. Feel free to copy this script and use it as a template for your own purposes.</p>
<pre class="r"><code>#sample parameters####

#how many total experimental groups will be included; if you&#39;re planning to use
#both sexes and consider biological sex as a factor in your analyses double it.
n.groups &lt;- 4

#desired sample size. This is something to discuss with your PI, but I usually
#tried to aim for at least 12 when examining behaviour
group.n &lt;- 12

totaln &lt;- n.groups*group.n

#timing parameters####

#to generate animals, start breeding 1 month before experiment begins. replace
#with desired start day, month, and year; separate using &quot;-&quot; or &quot;/&quot;
start.date  &lt;- dmy(&quot;07-09-2020&quot;) 

breeding &lt;- TRUE #will you be breeding the animals needed for this experiment?

#if you aren&#39;t breeding animals I&#39;ll assume they are being ordered from a
#commercial breeder, in which case we&#39;ll use the estiamted delivery date as the
#start date

intervention_days &lt;- 28  #how many days will the experimental intervention take?

b.testing_days &lt;- 7 #how many days will the behavioural testing take?

#Are you doing ex vivo electophysiology? Estimate about 2 days per animal per
#available ephys rig
ephys &lt;- TRUE
ephys.rigs &lt;- 4

#display parameter####
#provide an example of how you would like the dates displayed
my_stamp &lt;- stamp_date(&quot;Saturday, August 29th, 2020&quot;) </code></pre>
<p>From this point we can just run the script below and we’ll end up with an approximate schedule for our hypothetical behavioural neuroscience experiment. Don’t worry too much about the details of the conditional (if/else if/else) statements, we’ll cover that in a later post on R programming.</p>
<pre class="r"><code>exp_timeline &lt;- list() #define a list to hold experimental protocol components

#animal breeding####

#we&#39;ll store a version with modified display formatting separately so we can
#still perform calculations on d0
exp_timeline[[&quot;start_date&quot;]] &lt;- my_stamp(start.date) 

if(breeding == TRUE) {
  dob &lt;- start.date+28 #pups born
  exp_timeline[[&quot;pups_born&quot;]] &lt;- my_stamp(dob)
  #approximate weaning date####
  wd &lt;- dob + 21
  exp_timeline[[&quot;pups_weaned&quot;]] &lt;- my_stamp(wd)
}

#acclimatization period####

#acclimatization to maternal separation (if bred in house) or arrival at the
#animal facility (if ordered) (usually 1 week). After this point your animals
#are ready to participate in a behavioural experiment
if(breeding == TRUE) {
  ready.date &lt;- wd + 7  
  exp_timeline[[&quot;ready_date&quot;]] &lt;- my_stamp(ready.date)
} else {
  ready.date &lt;- start.date + 7
  exp_timeline[[&quot;ready_date&quot;]] &lt;- my_stamp(ready.date)
}

#intervention protocol####
if (intervention_days &gt; 0) {
  i.ds &lt;- ready.date + c(1:intervention_days)
  exp_timeline[[&quot;intervention&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,  
                                                                      c(1:intervention_days)), 
                                               &quot;date&quot; = my_stamp(i.ds))
  
}

#behavioural testing days####
#starting the day after the intervention is complete. if you haven&#39;t been
#handling the animals throughout the intervention period for at least 1 week
#then add as many days as needed to ensure the animals have been handled for at
#least 1 week
if (b.testing_days &gt; 0) {
  if (intervention_days &gt; 0) {
    if (intervention_days &lt; 7) {
      handling_days &lt;- 7 - intervention_days
      h.ds &lt;- i.ds[intervention_days] + c(1:handling_days)
      b.ds &lt;- h.ds[handling_days] + c(1:b.testing_days)
    } else {
      b.ds &lt;- i.ds[intervention_days] + c(1:b.testing_days)
    }
  } else if (intervention_days == 0) { 
    #if you were just doing behavioural testing an no postnatal intervention
    #e.g. for a transgenic to wild-type model comparison
    
    #add a week for handling where they should be handled for at least 1 minute
    #each per day for at least 5 of the days in the &quot;handling&quot; week
    handling_days &lt;- 7
    h.ds &lt;- ready.date + c(1:handling_days)
    
    b.ds &lt;- h.ds[7] + c(1:b.testing_days)
  }
  if (exists(&quot;h.ds&quot;)) {
    exp_timeline[[&quot;animal_handling&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,  
                                                                           c(1:handling_days)), 
                                                    &quot;date&quot; = my_stamp(h.ds))    
  } 
  exp_timeline[[&quot;behavioural_testing&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,  
                                                                             c(1:b.testing_days)), 
                                                      &quot;date&quot; = my_stamp(b.ds))
}

#electrophysiology days###
#for an exercise intervention study we could start doing ephys the day after behavioural testing is complete
if (ephys == T) {
  ephys.days &lt;- (totaln/2)/ephys.rigs
  
  if (b.testing_days &gt; 0) {
    e.ds &lt;- b.ds[b.testing_days] + c(1:ephys.days)
  } else if (b.testing_days == 0 &amp; intervention_days &gt; 0) { #if you only did an intervenion
    e.ds &lt;- i.ds[intervention_days] + c(1:ephys.days)
  } else if (b.testing_days == 0 &amp; intervention_days == 0) { #if you&#39;re only doing ephys
    e.ds &lt;- ready.date + c(1:ephys.days)
  }
  
  exp_timeline[[&quot;electrophysiology&quot;]] &lt;- data.frame(&quot;protocol_day&quot; = str_c(&quot;day #&quot;,
                                                                           c(1:ephys.days)), 
                                                    &quot;date&quot; = my_stamp(e.ds))
}

#determine how many days the experiment will take to complete up to the end of data collection####
if (exists(&quot;e.ds&quot;)) {
  exp_timeline[[&quot;total_days&quot;]] &lt;- e.ds[ephys.days] - start.date
  
} else if (exists(&quot;b.ds&quot;)) {
  exp_timeline[[&quot;total_days&quot;]] &lt;- b.ds[b.testing_days] - start.date
  
} else if (&quot;i.ds&quot;) { #if you only used an intervention and finished collecting data when it was over
  exp_timeline[[&quot;total_days&quot;]] &lt;- i.ds[intervention_days] - start.date
  
} </code></pre>
<p>After defining the parameters to use in constructing our experimental timeline and running the script, all we have to do to see it is print it to the console:</p>
<pre class="r"><code>exp_timeline</code></pre>
<pre><code>## $start_date
## [1] &quot;Monday, September 07th, 2020&quot;
## 
## $pups_born
## [1] &quot;Monday, October 05th, 2020&quot;
## 
## $pups_weaned
## [1] &quot;Monday, October 26th, 2020&quot;
## 
## $ready_date
## [1] &quot;Monday, November 02th, 2020&quot;
## 
## $intervention
##    protocol_day                           date
## 1        day #1   Tuesday, November 03th, 2020
## 2        day #2 Wednesday, November 04th, 2020
## 3        day #3  Thursday, November 05th, 2020
## 4        day #4    Friday, November 06th, 2020
## 5        day #5  Saturday, November 07th, 2020
## 6        day #6    Sunday, November 08th, 2020
## 7        day #7    Monday, November 09th, 2020
## 8        day #8   Tuesday, November 10th, 2020
## 9        day #9 Wednesday, November 11th, 2020
## 10      day #10  Thursday, November 12th, 2020
## 11      day #11    Friday, November 13th, 2020
## 12      day #12  Saturday, November 14th, 2020
## 13      day #13    Sunday, November 15th, 2020
## 14      day #14    Monday, November 16th, 2020
## 15      day #15   Tuesday, November 17th, 2020
## 16      day #16 Wednesday, November 18th, 2020
## 17      day #17  Thursday, November 19th, 2020
## 18      day #18    Friday, November 20th, 2020
## 19      day #19  Saturday, November 21th, 2020
## 20      day #20    Sunday, November 22th, 2020
## 21      day #21    Monday, November 23th, 2020
## 22      day #22   Tuesday, November 24th, 2020
## 23      day #23 Wednesday, November 25th, 2020
## 24      day #24  Thursday, November 26th, 2020
## 25      day #25    Friday, November 27th, 2020
## 26      day #26  Saturday, November 28th, 2020
## 27      day #27    Sunday, November 29th, 2020
## 28      day #28    Monday, November 30th, 2020
## 
## $behavioural_testing
##   protocol_day                           date
## 1       day #1   Tuesday, December 01th, 2020
## 2       day #2 Wednesday, December 02th, 2020
## 3       day #3  Thursday, December 03th, 2020
## 4       day #4    Friday, December 04th, 2020
## 5       day #5  Saturday, December 05th, 2020
## 6       day #6    Sunday, December 06th, 2020
## 7       day #7    Monday, December 07th, 2020
## 
## $electrophysiology
##   protocol_day                           date
## 1       day #1   Tuesday, December 08th, 2020
## 2       day #2 Wednesday, December 09th, 2020
## 3       day #3  Thursday, December 10th, 2020
## 4       day #4    Friday, December 11th, 2020
## 5       day #5  Saturday, December 12th, 2020
## 6       day #6    Sunday, December 13th, 2020
## 
## $total_days
## Time difference of 97 days</code></pre>
<p>There you have it. If you were doing this experiment, you’d know approximately which days each step of the protocol would fall on and how long it would take to get your data!</p>
<p>After reading all of this I hope you can see that working with factors or dates in R can be pretty easy when you leverage the forcats and tidyverse packages and you’ve even learned a few ways that they may benefit your research.</p>
</div>
<div id="navigation" class="section level1">
<h1><span class="header-section-number">7</span> Navigation</h1>
<p>Click <a href="https://craig.rbind.io/post/2020-06-28-asgr-2-3-string-manipulation/">here</a> to go back to the previous post on strings and regular expressions. A link to the next one will be added as soon as I have time to write it.</p>
</div>
<div id="notes" class="section level1">
<h1><span class="header-section-number">8</span> Notes</h1>
<ul>
<li><p>To learn more about factors and dates in R see <a href="https://r4ds.had.co.nz/factors.html">this chapter</a> and <a href="https://r4ds.had.co.nz/dates-and-times.html">this chapter</a> of <a href="https://r4ds.had.co.nz/">R 4 Data Science</a>.</p></li>
<li><p>If you want to go beyond basic date-based operations and calculations and can’t wait to learn about related analytical techniques like time-series analysis &amp; forecasting, I highly recommended checking out <a href="https://otexts.com/fpp3/">Forecasting: Principles and Practice</a> by Rob J. Hyndman and George Athanasopoulos at Monash University.</p></li>
</ul>
<p>Thank you for visiting my blog. I welcome any suggestions for future posts, comments or other feedback you might have. Feedback from beginners and science students/trainees (or with them in mind) is especially helpful in the interest of making this guide even better for them.</p>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>whiskers are plotted at 1.5x the interquartile range from the top &amp; bottom lines of the box or the maximum/minimum value if no values are above/below that 1.5*IQR threshold<a href="#fnref1" class="footnote-back">↩</a></p></li>
</ol>
</div>

    </div>

    

<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/r/">R</a>
  
  <a class="badge badge-light" href="/tags/r-basics/">R basics</a>
  
</div>



    
      








  





  
  <div class="media author-card" itemscope itemtype="http://schema.org/Person">
    
      
      <img class="portrait mr-3" src="/authors/admin/avatar_hu379968d4a591158aefc150dd1b891ba0_3685589_250x250_fill_q90_lanczos_center.jpg" itemprop="image" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title" itemprop="name"><a href="/authors/admin/">Dr. Craig P. Hutton</a></h5>
      <h6 class="card-subtitle">Data Scientist | Behavioural Neuroscientist</h6>
      
      <ul class="network-icon" aria-hidden="true">
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="/#contact" >
              <i class="fas fa-envelope"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://twitter.com/huttoncp" target="_blank" rel="noopener">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
        
          
          
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://scholar.google.ca/citations?user=bMNjAzkAAAAJ&amp;hl=en" target="_blank" rel="noopener">
              <i class="ai ai-google-scholar"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://github.com/huttoncp" target="_blank" rel="noopener">
              <i class="fab fa-github"></i>
            </a>
          </li>
        
      </ul>
    </div>
  </div>



      
      
      <div class="article-widget">
        <div class="hr-light"></div>
        <h3>Related</h3>
        <ul>
          
          <li><a href="/post/2020-08-29-asgr-2-5-dates/">A Scientist&#39;s Guide to R: Step 2.4 - forcats for factors</a></li>
          
          <li><a href="/post/2020-06-28-asgr-2-3-string-manipulation/">A Scientist&#39;s Guide to R: Step 2.3 - string manipulation and regex</a></li>
          
          <li><a href="/post/2020-03-29-asgr-2-2-joining-data/">A Scientist&#39;s Guide to R: Step 2.2 - Joining Data with dplyr</a></li>
          
          <li><a href="/post/2020-01-25-asgr-2-1-data-transformation-part-2/">A Scientist&#39;s Guide to R: Step 2.1 Data Transformation - part 2</a></li>
          
          <li><a href="/post/2019-12-30-asgr-2-1-data-transformation-part-1/">A Scientist&#39;s Guide to R: Step 2.1. Data Transformation - Part 1</a></li>
          
        </ul>
      </div>
      
    

    

    <div id="disqus_thread"></div>
<script>
(function() {
var d = document, s = d.createElement('script');
s.src = 'https://craig-rbind-io.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

  </div>
</article>

<div class="container">
  <footer class="site-footer">
  
  <p class="powered-by">
    <a href="/privacy/">Privacy Policy</a>
  </p>
  

  <p class="powered-by">
    Copyright © 2020 by Craig P. Hutton &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

</div>


<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

    

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js" integrity="sha256-aYTdUrn6Ow1DDgh5JTc3aDGnnju48y/1c8s1dgkYPQ8=" crossorigin="anonymous"></script>
        
      

      
      
    

    
    

    
    
    
    <script id="dsq-count-scr" src="//craig-rbind-io.disqus.com/count.js" async></script>
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.ee8463f2a394889d45e169a983fe913d.js"></script>

  </body>
</html>

